// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// mrd_DeepState_TestHarness_generation.cpp and mrd_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector mrd(NumericVector dm, NumericVector cd);

TEST(dbscan_deepstate_test,mrd_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector dm  = RcppDeepState_NumericVector();
  std::string dm_t = "/home/akhila/fuzzer_packages/fuzzedpackages/dbscan/inst/testfiles/mrd/libFuzzer_mrd/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_dm.qs";
  qs::c_qsave(dm,dm_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "dm values: "<< dm << std::endl;
  NumericVector cd  = RcppDeepState_NumericVector();
  std::string cd_t = "/home/akhila/fuzzer_packages/fuzzedpackages/dbscan/inst/testfiles/mrd/libFuzzer_mrd/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_cd.qs";
  qs::c_qsave(cd,cd_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "cd values: "<< cd << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    mrd(dm,cd);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
