// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// do_range_dbl_DeepState_TestHarness_generation.cpp and do_range_dbl_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

DoubleVector do_range_dbl(NumericVector x, double halt_if_min, double halt_if_max);

TEST(hutilscpp_deepstate_test,do_range_dbl_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector x  = RcppDeepState_NumericVector();
  std::string x_t = "/home/akhila/fuzzer_packages/fuzzedpackages/hutilscpp/inst/testfiles/do_range_dbl/libFuzzer_do_range_dbl/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_x.qs";
  qs::c_qsave(x,x_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  NumericVector halt_if_min(1);
  halt_if_min[0]  = RcppDeepState_double();
  std::string halt_if_min_t = "/home/akhila/fuzzer_packages/fuzzedpackages/hutilscpp/inst/testfiles/do_range_dbl/libFuzzer_do_range_dbl/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_halt_if_min.qs";
  qs::c_qsave(halt_if_min,halt_if_min_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "halt_if_min values: "<< halt_if_min << std::endl;
  NumericVector halt_if_max(1);
  halt_if_max[0]  = RcppDeepState_double();
  std::string halt_if_max_t = "/home/akhila/fuzzer_packages/fuzzedpackages/hutilscpp/inst/testfiles/do_range_dbl/libFuzzer_do_range_dbl/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_halt_if_max.qs";
  qs::c_qsave(halt_if_max,halt_if_max_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "halt_if_max values: "<< halt_if_max << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    do_range_dbl(x,halt_if_min[0],halt_if_max[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
