// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// stable_rnd_DeepState_TestHarness_generation.cpp and stable_rnd_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector stable_rnd(int N, NumericVector pars, int parametrization);

TEST(libstableR_deepstate_test,stable_rnd_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector N(1);
  N[0]  = RcppDeepState_int();
  std::string N_t = "/home/akhila/fuzzer_packages/fuzzedpackages/libstableR/inst/testfiles/stable_rnd/AFL_stable_rnd/afl_inputs/" + std::to_string(t) + "_N.qs";
  qs::c_qsave(N,N_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "N values: "<< N << std::endl;
  NumericVector pars  = RcppDeepState_NumericVector();
  std::string pars_t = "/home/akhila/fuzzer_packages/fuzzedpackages/libstableR/inst/testfiles/stable_rnd/AFL_stable_rnd/afl_inputs/" + std::to_string(t) + "_pars.qs";
  qs::c_qsave(pars,pars_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "pars values: "<< pars << std::endl;
  IntegerVector parametrization(1);
  parametrization[0]  = RcppDeepState_int();
  std::string parametrization_t = "/home/akhila/fuzzer_packages/fuzzedpackages/libstableR/inst/testfiles/stable_rnd/AFL_stable_rnd/afl_inputs/" + std::to_string(t) + "_parametrization.qs";
  qs::c_qsave(parametrization,parametrization_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "parametrization values: "<< parametrization << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    stable_rnd(N[0],pars,parametrization[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
