// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// repmat_DeepState_TestHarness_generation.cpp and repmat_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix repmat(NumericMatrix x, int nrow, int ncol);

TEST(MESS_deepstate_test,repmat_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix x  = RcppDeepState_NumericMatrix();
  std::string x_t = "/home/akhila/fuzzer_packages/fuzzedpackages/MESS/inst/testfiles/repmat/libFuzzer_repmat/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_x.qs";
  qs::c_qsave(x,x_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  IntegerVector nrow(1);
  nrow[0]  = RcppDeepState_int();
  std::string nrow_t = "/home/akhila/fuzzer_packages/fuzzedpackages/MESS/inst/testfiles/repmat/libFuzzer_repmat/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_nrow.qs";
  qs::c_qsave(nrow,nrow_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nrow values: "<< nrow << std::endl;
  IntegerVector ncol(1);
  ncol[0]  = RcppDeepState_int();
  std::string ncol_t = "/home/akhila/fuzzer_packages/fuzzedpackages/MESS/inst/testfiles/repmat/libFuzzer_repmat/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_ncol.qs";
  qs::c_qsave(ncol,ncol_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ncol values: "<< ncol << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    repmat(x,nrow[0],ncol[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
