// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// test_dims2columns_DeepState_TestHarness_generation.cpp and test_dims2columns_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

IntegerVector test_dims2columns(const NumericVector cpt, const CharacterVector class_var, const CharacterVector columns_db);

TEST(bnclassify_deepstate_test,test_dims2columns_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector cpt  = RcppDeepState_NumericVector();
  std::string cpt_t = "/home/akhila/fuzzer_packages/fuzzedpackages/bnclassify/inst/testfiles/test_dims2columns/AFL_test_dims2columns/afl_inputs/" + std::to_string(t) + "_cpt.qs";
  qs::c_qsave(cpt,cpt_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "cpt values: "<< cpt << std::endl;
  CharacterVector class_var  = RcppDeepState_CharacterVector();
  std::string class_var_t = "/home/akhila/fuzzer_packages/fuzzedpackages/bnclassify/inst/testfiles/test_dims2columns/AFL_test_dims2columns/afl_inputs/" + std::to_string(t) + "_class_var.qs";
  qs::c_qsave(class_var,class_var_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "class_var values: "<< class_var << std::endl;
  CharacterVector columns_db  = RcppDeepState_CharacterVector();
  std::string columns_db_t = "/home/akhila/fuzzer_packages/fuzzedpackages/bnclassify/inst/testfiles/test_dims2columns/AFL_test_dims2columns/afl_inputs/" + std::to_string(t) + "_columns_db.qs";
  qs::c_qsave(columns_db,columns_db_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "columns_db values: "<< columns_db << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    test_dims2columns(cpt,class_var,columns_db);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
