// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// tqdist_PairsQuartetDistance_DeepState_TestHarness_generation.cpp and tqdist_PairsQuartetDistance_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

IntegerVector tqdist_PairsQuartetDistance(CharacterVector file1, CharacterVector file2);

TEST(Quartet_deepstate_test,tqdist_PairsQuartetDistance_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  CharacterVector file1  = RcppDeepState_CharacterVector();
  std::string file1_t = "/home/akhila/fuzzer_packages/fuzzedpackages/Quartet/inst/testfiles/tqdist_PairsQuartetDistance/libFuzzer_tqdist_PairsQuartetDistance/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_file1.qs";
  qs::c_qsave(file1,file1_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "file1 values: "<< file1 << std::endl;
  CharacterVector file2  = RcppDeepState_CharacterVector();
  std::string file2_t = "/home/akhila/fuzzer_packages/fuzzedpackages/Quartet/inst/testfiles/tqdist_PairsQuartetDistance/libFuzzer_tqdist_PairsQuartetDistance/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_file2.qs";
  qs::c_qsave(file2,file2_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "file2 values: "<< file2 << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    tqdist_PairsQuartetDistance(file1,file2);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
