// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// lik_DeepState_TestHarness_generation.cpp and lik_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double lik(NumericVector S, NumericVector pi, NumericVector ncens, NumericVector nuncens);

TEST(DStree_deepstate_test,lik_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector S  = RcppDeepState_NumericVector();
  std::string S_t = "/home/akhila/fuzzer_packages/fuzzedpackages/DStree/inst/testfiles/lik/libFuzzer_lik/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_S.qs";
  qs::c_qsave(S,S_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "S values: "<< S << std::endl;
  NumericVector pi  = RcppDeepState_NumericVector();
  std::string pi_t = "/home/akhila/fuzzer_packages/fuzzedpackages/DStree/inst/testfiles/lik/libFuzzer_lik/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_pi.qs";
  qs::c_qsave(pi,pi_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "pi values: "<< pi << std::endl;
  NumericVector ncens  = RcppDeepState_NumericVector();
  std::string ncens_t = "/home/akhila/fuzzer_packages/fuzzedpackages/DStree/inst/testfiles/lik/libFuzzer_lik/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_ncens.qs";
  qs::c_qsave(ncens,ncens_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ncens values: "<< ncens << std::endl;
  NumericVector nuncens  = RcppDeepState_NumericVector();
  std::string nuncens_t = "/home/akhila/fuzzer_packages/fuzzedpackages/DStree/inst/testfiles/lik/libFuzzer_lik/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_nuncens.qs";
  qs::c_qsave(nuncens,nuncens_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nuncens values: "<< nuncens << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    lik(S,pi,ncens,nuncens);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
