// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// cpp_computeGamma_DeepState_TestHarness_generation.cpp and cpp_computeGamma_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double cpp_computeGamma(const Rcpp::NumericVector V);

TEST(IFC_deepstate_test,cpp_computeGamma_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector V  = RcppDeepState_NumericVector();
  std::string V_t = "/home/akhila/fuzzer_packages/fuzzedpackages/IFC/inst/testfiles/cpp_computeGamma/libFuzzer_cpp_computeGamma/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_V.qs";
  qs::c_qsave(V,V_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "V values: "<< V << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    cpp_computeGamma(V);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
