// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// integrate_DeepState_TestHarness_generation.cpp and integrate_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double integrate(Rcpp::NumericVector x, Rcpp::NumericVector fx);

TEST(irt_deepstate_test,integrate_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector x  = RcppDeepState_NumericVector();
  std::string x_t = "/home/akhila/fuzzer_packages/fuzzedpackages/irt/inst/testfiles/integrate/libFuzzer_integrate/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_x.qs";
  qs::c_qsave(x,x_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  NumericVector fx  = RcppDeepState_NumericVector();
  std::string fx_t = "/home/akhila/fuzzer_packages/fuzzedpackages/irt/inst/testfiles/integrate/libFuzzer_integrate/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_fx.qs";
  qs::c_qsave(fx,fx_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "fx values: "<< fx << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    integrate(x,fx);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
