// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// get_gnp_DeepState_TestHarness_generation.cpp and get_gnp_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector get_gnp(NumericVector nodes_at_depth, int grow_node);

TEST(bartBMA_deepstate_test,get_gnp_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector nodes_at_depth  = RcppDeepState_NumericVector();
  std::string nodes_at_depth_t = "/home/akhila/fuzzer_packages/fuzzedpackages/bartBMA/inst/testfiles/get_gnp/libFuzzer_get_gnp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_nodes_at_depth.qs";
  qs::c_qsave(nodes_at_depth,nodes_at_depth_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nodes_at_depth values: "<< nodes_at_depth << std::endl;
  IntegerVector grow_node(1);
  grow_node[0]  = RcppDeepState_int();
  std::string grow_node_t = "/home/akhila/fuzzer_packages/fuzzedpackages/bartBMA/inst/testfiles/get_gnp/libFuzzer_get_gnp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_grow_node.qs";
  qs::c_qsave(grow_node,grow_node_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "grow_node values: "<< grow_node << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    get_gnp(nodes_at_depth,grow_node[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
