// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// FmeasureC_no0_DeepState_TestHarness_generation.cpp and FmeasureC_no0_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double FmeasureC_no0(NumericVector pred, NumericVector ref);

TEST(cytometree_deepstate_test,FmeasureC_no0_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector pred  = RcppDeepState_NumericVector();
  std::string pred_t = "/home/akhila/fuzzer_packages/fuzzedpackages/cytometree/inst/testfiles/FmeasureC_no0/AFL_FmeasureC_no0/afl_inputs/" + std::to_string(t) + "_pred.qs";
  qs::c_qsave(pred,pred_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "pred values: "<< pred << std::endl;
  NumericVector ref  = RcppDeepState_NumericVector();
  std::string ref_t = "/home/akhila/fuzzer_packages/fuzzedpackages/cytometree/inst/testfiles/FmeasureC_no0/AFL_FmeasureC_no0/afl_inputs/" + std::to_string(t) + "_ref.qs";
  qs::c_qsave(ref,ref_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ref values: "<< ref << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    FmeasureC_no0(pred,ref);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
