// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// ColSum_C_DeepState_TestHarness_generation.cpp and ColSum_C_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector ColSum_C(NumericMatrix AA);

TEST(CKLRT_deepstate_test,ColSum_C_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix AA  = RcppDeepState_NumericMatrix();
  std::string AA_t = "/home/akhila/fuzzer_packages/fuzzedpackages/CKLRT/inst/testfiles/ColSum_C/AFL_ColSum_C/afl_inputs/" + std::to_string(t) + "_AA.qs";
  qs::c_qsave(AA,AA_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "AA values: "<< AA << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    ColSum_C(AA);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
