// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// rcpp_distance_haversine_DeepState_TestHarness_generation.cpp and rcpp_distance_haversine_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::NumericVector rcpp_distance_haversine(Rcpp::NumericVector latFrom, Rcpp::NumericVector lonFrom, Rcpp::NumericVector latTo, Rcpp::NumericVector lonTo, double tolerance);

TEST(gtfs2gps_deepstate_test,rcpp_distance_haversine_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector latFrom  = RcppDeepState_NumericVector();
  std::string latFrom_t = "/home/akhila/fuzzer_packages/fuzzedpackages/gtfs2gps/inst/testfiles/rcpp_distance_haversine/AFL_rcpp_distance_haversine/afl_inputs/" + std::to_string(t) + "_latFrom.qs";
  qs::c_qsave(latFrom,latFrom_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "latFrom values: "<< latFrom << std::endl;
  NumericVector lonFrom  = RcppDeepState_NumericVector();
  std::string lonFrom_t = "/home/akhila/fuzzer_packages/fuzzedpackages/gtfs2gps/inst/testfiles/rcpp_distance_haversine/AFL_rcpp_distance_haversine/afl_inputs/" + std::to_string(t) + "_lonFrom.qs";
  qs::c_qsave(lonFrom,lonFrom_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "lonFrom values: "<< lonFrom << std::endl;
  NumericVector latTo  = RcppDeepState_NumericVector();
  std::string latTo_t = "/home/akhila/fuzzer_packages/fuzzedpackages/gtfs2gps/inst/testfiles/rcpp_distance_haversine/AFL_rcpp_distance_haversine/afl_inputs/" + std::to_string(t) + "_latTo.qs";
  qs::c_qsave(latTo,latTo_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "latTo values: "<< latTo << std::endl;
  NumericVector lonTo  = RcppDeepState_NumericVector();
  std::string lonTo_t = "/home/akhila/fuzzer_packages/fuzzedpackages/gtfs2gps/inst/testfiles/rcpp_distance_haversine/AFL_rcpp_distance_haversine/afl_inputs/" + std::to_string(t) + "_lonTo.qs";
  qs::c_qsave(lonTo,lonTo_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "lonTo values: "<< lonTo << std::endl;
  NumericVector tolerance(1);
  tolerance[0]  = RcppDeepState_double();
  std::string tolerance_t = "/home/akhila/fuzzer_packages/fuzzedpackages/gtfs2gps/inst/testfiles/rcpp_distance_haversine/AFL_rcpp_distance_haversine/afl_inputs/" + std::to_string(t) + "_tolerance.qs";
  qs::c_qsave(tolerance,tolerance_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tolerance values: "<< tolerance << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    rcpp_distance_haversine(latFrom,lonFrom,latTo,lonTo,tolerance[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
