// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// interpolateAkimaGrid_DeepState_TestHarness_generation.cpp and interpolateAkimaGrid_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

void interpolateAkimaGrid(NumericVector x, NumericVector y, NumericMatrix grid, NumericMatrix output);

TEST(ProFound_deepstate_test,interpolateAkimaGrid_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector x  = RcppDeepState_NumericVector();
  std::string x_t = "/home/akhila/fuzzer_packages/fuzzedpackages/ProFound/inst/testfiles/interpolateAkimaGrid/AFL_interpolateAkimaGrid/afl_inputs/" + std::to_string(t) + "_x.qs";
  qs::c_qsave(x,x_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  NumericVector y  = RcppDeepState_NumericVector();
  std::string y_t = "/home/akhila/fuzzer_packages/fuzzedpackages/ProFound/inst/testfiles/interpolateAkimaGrid/AFL_interpolateAkimaGrid/afl_inputs/" + std::to_string(t) + "_y.qs";
  qs::c_qsave(y,y_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "y values: "<< y << std::endl;
  NumericMatrix grid  = RcppDeepState_NumericMatrix();
  std::string grid_t = "/home/akhila/fuzzer_packages/fuzzedpackages/ProFound/inst/testfiles/interpolateAkimaGrid/AFL_interpolateAkimaGrid/afl_inputs/" + std::to_string(t) + "_grid.qs";
  qs::c_qsave(grid,grid_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "grid values: "<< grid << std::endl;
  NumericMatrix output  = RcppDeepState_NumericMatrix();
  std::string output_t = "/home/akhila/fuzzer_packages/fuzzedpackages/ProFound/inst/testfiles/interpolateAkimaGrid/AFL_interpolateAkimaGrid/afl_inputs/" + std::to_string(t) + "_output.qs";
  qs::c_qsave(output,output_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "output values: "<< output << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    interpolateAkimaGrid(x,y,grid,output);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
