// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// C_Akritas_DeepState_TestHarness_generation.cpp and C_Akritas_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector C_Akritas(NumericMatrix truth, NumericVector times, NumericVector unique_times, NumericVector FX_train, NumericVector FX_predict, double lambda);

TEST(survivalmodels_deepstate_test,C_Akritas_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix truth  = RcppDeepState_NumericMatrix();
  std::string truth_t = "/home/akhila/fuzzer_packages/fuzzedpackages/survivalmodels/inst/testfiles/C_Akritas/AFL_C_Akritas/afl_inputs/" + std::to_string(t) + "_truth.qs";
  qs::c_qsave(truth,truth_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "truth values: "<< truth << std::endl;
  NumericVector times  = RcppDeepState_NumericVector();
  std::string times_t = "/home/akhila/fuzzer_packages/fuzzedpackages/survivalmodels/inst/testfiles/C_Akritas/AFL_C_Akritas/afl_inputs/" + std::to_string(t) + "_times.qs";
  qs::c_qsave(times,times_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "times values: "<< times << std::endl;
  NumericVector unique_times  = RcppDeepState_NumericVector();
  std::string unique_times_t = "/home/akhila/fuzzer_packages/fuzzedpackages/survivalmodels/inst/testfiles/C_Akritas/AFL_C_Akritas/afl_inputs/" + std::to_string(t) + "_unique_times.qs";
  qs::c_qsave(unique_times,unique_times_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "unique_times values: "<< unique_times << std::endl;
  NumericVector FX_train  = RcppDeepState_NumericVector();
  std::string FX_train_t = "/home/akhila/fuzzer_packages/fuzzedpackages/survivalmodels/inst/testfiles/C_Akritas/AFL_C_Akritas/afl_inputs/" + std::to_string(t) + "_FX_train.qs";
  qs::c_qsave(FX_train,FX_train_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "FX_train values: "<< FX_train << std::endl;
  NumericVector FX_predict  = RcppDeepState_NumericVector();
  std::string FX_predict_t = "/home/akhila/fuzzer_packages/fuzzedpackages/survivalmodels/inst/testfiles/C_Akritas/AFL_C_Akritas/afl_inputs/" + std::to_string(t) + "_FX_predict.qs";
  qs::c_qsave(FX_predict,FX_predict_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "FX_predict values: "<< FX_predict << std::endl;
  NumericVector lambda(1);
  lambda[0]  = RcppDeepState_double();
  std::string lambda_t = "/home/akhila/fuzzer_packages/fuzzedpackages/survivalmodels/inst/testfiles/C_Akritas/AFL_C_Akritas/afl_inputs/" + std::to_string(t) + "_lambda.qs";
  qs::c_qsave(lambda,lambda_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "lambda values: "<< lambda << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    C_Akritas(truth,times,unique_times,FX_train,FX_predict,lambda[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
