// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// sorted_range_search_DeepState_TestHarness_generation.cpp and sorted_range_search_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

LogicalVector sorted_range_search(NumericVector x, double lower, double upper);

TEST(tibbletime_deepstate_test,sorted_range_search_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector x  = RcppDeepState_NumericVector();
  std::string x_t = "/home/akhila/fuzzer_packages/fuzzedpackages/tibbletime/inst/testfiles/sorted_range_search/libFuzzer_sorted_range_search/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_x.qs";
  qs::c_qsave(x,x_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  NumericVector lower(1);
  lower[0]  = RcppDeepState_double();
  std::string lower_t = "/home/akhila/fuzzer_packages/fuzzedpackages/tibbletime/inst/testfiles/sorted_range_search/libFuzzer_sorted_range_search/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_lower.qs";
  qs::c_qsave(lower,lower_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "lower values: "<< lower << std::endl;
  NumericVector upper(1);
  upper[0]  = RcppDeepState_double();
  std::string upper_t = "/home/akhila/fuzzer_packages/fuzzedpackages/tibbletime/inst/testfiles/sorted_range_search/libFuzzer_sorted_range_search/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_upper.qs";
  qs::c_qsave(upper,upper_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "upper values: "<< upper << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    sorted_range_search(x,lower[0],upper[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
