// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// SizeEstimate__DeepState_TestHarness_generation.cpp and SizeEstimate__DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector SizeEstimate_(NumericVector tesselation);

TEST(icosa_deepstate_test,SizeEstimate__test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector tesselation  = RcppDeepState_NumericVector();
  std::string tesselation_t = "/home/akhila/fuzzer_packages/fuzzedpackages/icosa/inst/testfiles/SizeEstimate_/libFuzzer_SizeEstimate_/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_tesselation.qs";
  qs::c_qsave(tesselation,tesselation_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tesselation values: "<< tesselation << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    SizeEstimate_(tesselation);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
