// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// Refine2d__DeepState_TestHarness_generation.cpp and Refine2d__DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix Refine2d_(NumericMatrix From, int breaks);

TEST(icosa_deepstate_test,Refine2d__test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix From  = RcppDeepState_NumericMatrix();
  std::string From_t = "/home/akhila/fuzzer_packages/fuzzedpackages/icosa/inst/testfiles/Refine2d_/libFuzzer_Refine2d_/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_From.qs";
  qs::c_qsave(From,From_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "From values: "<< From << std::endl;
  IntegerVector breaks(1);
  breaks[0]  = RcppDeepState_int();
  std::string breaks_t = "/home/akhila/fuzzer_packages/fuzzedpackages/icosa/inst/testfiles/Refine2d_/libFuzzer_Refine2d_/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_breaks.qs";
  qs::c_qsave(breaks,breaks_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "breaks values: "<< breaks << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    Refine2d_(From,breaks[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
