// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// C_disj_conCov_DeepState_TestHarness_generation.cpp and C_disj_conCov_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector C_disj_conCov(const IntegerVector cols, const NumericMatrix x, const NumericVector y, const IntegerVector f);

TEST(cna_deepstate_test,C_disj_conCov_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector cols  = RcppDeepState_IntegerVector();
  std::string cols_t = "/home/akhila/fuzzer_packages/fuzzedpackages/cna/inst/testfiles/C_disj_conCov/AFL_C_disj_conCov/afl_inputs/" + std::to_string(t) + "_cols.qs";
  qs::c_qsave(cols,cols_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "cols values: "<< cols << std::endl;
  NumericMatrix x  = RcppDeepState_NumericMatrix();
  std::string x_t = "/home/akhila/fuzzer_packages/fuzzedpackages/cna/inst/testfiles/C_disj_conCov/AFL_C_disj_conCov/afl_inputs/" + std::to_string(t) + "_x.qs";
  qs::c_qsave(x,x_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  NumericVector y  = RcppDeepState_NumericVector();
  std::string y_t = "/home/akhila/fuzzer_packages/fuzzedpackages/cna/inst/testfiles/C_disj_conCov/AFL_C_disj_conCov/afl_inputs/" + std::to_string(t) + "_y.qs";
  qs::c_qsave(y,y_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "y values: "<< y << std::endl;
  IntegerVector f  = RcppDeepState_IntegerVector();
  std::string f_t = "/home/akhila/fuzzer_packages/fuzzedpackages/cna/inst/testfiles/C_disj_conCov/AFL_C_disj_conCov/afl_inputs/" + std::to_string(t) + "_f.qs";
  qs::c_qsave(f,f_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "f values: "<< f << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    C_disj_conCov(cols,x,y,f);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
