// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// tqdist_QuartetAgreementChar_DeepState_TestHarness_generation.cpp and tqdist_QuartetAgreementChar_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

IntegerVector tqdist_QuartetAgreementChar(CharacterVector string1, CharacterVector string2);

TEST(Quartet_deepstate_test,tqdist_QuartetAgreementChar_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  CharacterVector string1  = RcppDeepState_CharacterVector();
  std::string string1_t = "/home/akhila/fuzzer_packages/fuzzedpackages/Quartet/inst/testfiles/tqdist_QuartetAgreementChar/libFuzzer_tqdist_QuartetAgreementChar/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_string1.qs";
  qs::c_qsave(string1,string1_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "string1 values: "<< string1 << std::endl;
  CharacterVector string2  = RcppDeepState_CharacterVector();
  std::string string2_t = "/home/akhila/fuzzer_packages/fuzzedpackages/Quartet/inst/testfiles/tqdist_QuartetAgreementChar/libFuzzer_tqdist_QuartetAgreementChar/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_string2.qs";
  qs::c_qsave(string2,string2_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "string2 values: "<< string2 << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    tqdist_QuartetAgreementChar(string1,string2);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
