// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// mrd_m_DeepState_TestHarness_generation.cpp and mrd_m_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix mrd_m(NumericMatrix dm, NumericVector cd);

TEST(dbscan_deepstate_test,mrd_m_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix dm  = RcppDeepState_NumericMatrix();
  std::string dm_t = "/home/akhila/fuzzer_packages/fuzzedpackages/dbscan/inst/testfiles/mrd_m/AFL_mrd_m/afl_inputs/" + std::to_string(t) + "_dm.qs";
  qs::c_qsave(dm,dm_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "dm values: "<< dm << std::endl;
  NumericVector cd  = RcppDeepState_NumericVector();
  std::string cd_t = "/home/akhila/fuzzer_packages/fuzzedpackages/dbscan/inst/testfiles/mrd_m/AFL_mrd_m/afl_inputs/" + std::to_string(t) + "_cd.qs";
  qs::c_qsave(cd,cd_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "cd values: "<< cd << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    mrd_m(dm,cd);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
