// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// vusC_full_core_DeepState_TestHarness_generation.cpp and vusC_full_core_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List vusC_full_core(NumericVector tt1, NumericVector tt2, NumericVector tt3);

TEST(bcROCsurface_deepstate_test,vusC_full_core_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector tt1  = RcppDeepState_NumericVector();
  std::string tt1_t = "/home/akhila/fuzzer_packages/fuzzedpackages/bcROCsurface/inst/testfiles/vusC_full_core/libFuzzer_vusC_full_core/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_tt1.qs";
  qs::c_qsave(tt1,tt1_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tt1 values: "<< tt1 << std::endl;
  NumericVector tt2  = RcppDeepState_NumericVector();
  std::string tt2_t = "/home/akhila/fuzzer_packages/fuzzedpackages/bcROCsurface/inst/testfiles/vusC_full_core/libFuzzer_vusC_full_core/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_tt2.qs";
  qs::c_qsave(tt2,tt2_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tt2 values: "<< tt2 << std::endl;
  NumericVector tt3  = RcppDeepState_NumericVector();
  std::string tt3_t = "/home/akhila/fuzzer_packages/fuzzedpackages/bcROCsurface/inst/testfiles/vusC_full_core/libFuzzer_vusC_full_core/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_tt3.qs";
  qs::c_qsave(tt3,tt3_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tt3 values: "<< tt3 << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    vusC_full_core(tt1,tt2,tt3);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
