// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// ExpandEdgesByFacesTri__DeepState_TestHarness_generation.cpp and ExpandEdgesByFacesTri__DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix ExpandEdgesByFacesTri_(NumericMatrix origV, NumericMatrix origSubF, NumericVector center, int breaks);

TEST(icosa_deepstate_test,ExpandEdgesByFacesTri__test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix origV  = RcppDeepState_NumericMatrix();
  std::string origV_t = "/home/akhila/fuzzer_packages/fuzzedpackages/icosa/inst/testfiles/ExpandEdgesByFacesTri_/AFL_ExpandEdgesByFacesTri_/afl_inputs/" + std::to_string(t) + "_origV.qs";
  qs::c_qsave(origV,origV_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "origV values: "<< origV << std::endl;
  NumericMatrix origSubF  = RcppDeepState_NumericMatrix();
  std::string origSubF_t = "/home/akhila/fuzzer_packages/fuzzedpackages/icosa/inst/testfiles/ExpandEdgesByFacesTri_/AFL_ExpandEdgesByFacesTri_/afl_inputs/" + std::to_string(t) + "_origSubF.qs";
  qs::c_qsave(origSubF,origSubF_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "origSubF values: "<< origSubF << std::endl;
  NumericVector center  = RcppDeepState_NumericVector();
  std::string center_t = "/home/akhila/fuzzer_packages/fuzzedpackages/icosa/inst/testfiles/ExpandEdgesByFacesTri_/AFL_ExpandEdgesByFacesTri_/afl_inputs/" + std::to_string(t) + "_center.qs";
  qs::c_qsave(center,center_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "center values: "<< center << std::endl;
  IntegerVector breaks(1);
  breaks[0]  = RcppDeepState_int();
  std::string breaks_t = "/home/akhila/fuzzer_packages/fuzzedpackages/icosa/inst/testfiles/ExpandEdgesByFacesTri_/AFL_ExpandEdgesByFacesTri_/afl_inputs/" + std::to_string(t) + "_breaks.qs";
  qs::c_qsave(breaks,breaks_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "breaks values: "<< breaks << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    ExpandEdgesByFacesTri_(origV,origSubF,center,breaks[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
