// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// hermite_function_DeepState_TestHarness_generation.cpp and hermite_function_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix hermite_function(int N, NumericVector x, NumericVector normalization);

TEST(hermiter_deepstate_test,hermite_function_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector N(1);
  N[0]  = RcppDeepState_int();
  std::string N_t = "/home/akhila/fuzzer_packages/fuzzedpackages/hermiter/inst/testfiles/hermite_function/libFuzzer_hermite_function/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_N.qs";
  qs::c_qsave(N,N_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "N values: "<< N << std::endl;
  NumericVector x  = RcppDeepState_NumericVector();
  std::string x_t = "/home/akhila/fuzzer_packages/fuzzedpackages/hermiter/inst/testfiles/hermite_function/libFuzzer_hermite_function/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_x.qs";
  qs::c_qsave(x,x_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  NumericVector normalization  = RcppDeepState_NumericVector();
  std::string normalization_t = "/home/akhila/fuzzer_packages/fuzzedpackages/hermiter/inst/testfiles/hermite_function/libFuzzer_hermite_function/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_normalization.qs";
  qs::c_qsave(normalization,normalization_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "normalization values: "<< normalization << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    hermite_function(N[0],x,normalization);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
