// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// compute_counts_DeepState_TestHarness_generation.cpp and compute_counts_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List compute_counts(CharacterVector input_data, IntegerVector depth);

TEST(BCT_deepstate_test,compute_counts_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  CharacterVector input_data  = RcppDeepState_CharacterVector();
  std::string input_data_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BCT/inst/testfiles/compute_counts/AFL_compute_counts/afl_inputs/" + std::to_string(t) + "_input_data.qs";
  qs::c_qsave(input_data,input_data_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "input_data values: "<< input_data << std::endl;
  IntegerVector depth  = RcppDeepState_IntegerVector();
  std::string depth_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BCT/inst/testfiles/compute_counts/AFL_compute_counts/afl_inputs/" + std::to_string(t) + "_depth.qs";
  qs::c_qsave(depth,depth_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "depth values: "<< depth << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    compute_counts(input_data,depth);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
