// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// hmode_DeepState_TestHarness_generation.cpp and hmode_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double hmode(NumericVector x, double cip);

TEST(waspr_deepstate_test,hmode_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector x  = RcppDeepState_NumericVector();
  std::string x_t = "/home/akhila/fuzzer_packages/fuzzedpackages/waspr/inst/testfiles/hmode/libFuzzer_hmode/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_x.qs";
  qs::c_qsave(x,x_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  NumericVector cip(1);
  cip[0]  = RcppDeepState_double();
  std::string cip_t = "/home/akhila/fuzzer_packages/fuzzedpackages/waspr/inst/testfiles/hmode/libFuzzer_hmode/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_cip.qs";
  qs::c_qsave(cip,cip_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "cip values: "<< cip << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    hmode(x,cip[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
