// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// cdm_rcpp_sim_model_item_responses_DeepState_TestHarness_generation.cpp and cdm_rcpp_sim_model_item_responses_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::NumericMatrix cdm_rcpp_sim_model_item_responses(Rcpp::IntegerVector theta_index, Rcpp::NumericVector irfprob, Rcpp::IntegerVector dim_irfprob);

TEST(CDM_deepstate_test,cdm_rcpp_sim_model_item_responses_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector theta_index  = RcppDeepState_IntegerVector();
  std::string theta_index_t = "/home/akhila/fuzzer_packages/fuzzedpackages/CDM/inst/testfiles/cdm_rcpp_sim_model_item_responses/AFL_cdm_rcpp_sim_model_item_responses/afl_inputs/" + std::to_string(t) + "_theta_index.qs";
  qs::c_qsave(theta_index,theta_index_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "theta_index values: "<< theta_index << std::endl;
  NumericVector irfprob  = RcppDeepState_NumericVector();
  std::string irfprob_t = "/home/akhila/fuzzer_packages/fuzzedpackages/CDM/inst/testfiles/cdm_rcpp_sim_model_item_responses/AFL_cdm_rcpp_sim_model_item_responses/afl_inputs/" + std::to_string(t) + "_irfprob.qs";
  qs::c_qsave(irfprob,irfprob_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "irfprob values: "<< irfprob << std::endl;
  IntegerVector dim_irfprob  = RcppDeepState_IntegerVector();
  std::string dim_irfprob_t = "/home/akhila/fuzzer_packages/fuzzedpackages/CDM/inst/testfiles/cdm_rcpp_sim_model_item_responses/AFL_cdm_rcpp_sim_model_item_responses/afl_inputs/" + std::to_string(t) + "_dim_irfprob.qs";
  qs::c_qsave(dim_irfprob,dim_irfprob_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "dim_irfprob values: "<< dim_irfprob << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    cdm_rcpp_sim_model_item_responses(theta_index,irfprob,dim_irfprob);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
