// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// MaxMincpp_DeepState_TestHarness_generation.cpp and MaxMincpp_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

IntegerVector MaxMincpp(NumericMatrix locations);

TEST(GPvecchia_deepstate_test,MaxMincpp_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix locations  = RcppDeepState_NumericMatrix();
  std::string locations_t = "/home/akhila/fuzzer_packages/fuzzedpackages/GPvecchia/inst/testfiles/MaxMincpp/libFuzzer_MaxMincpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_locations.qs";
  qs::c_qsave(locations,locations_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "locations values: "<< locations << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    MaxMincpp(locations);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
