// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// EdgesFromPoints__DeepState_TestHarness_generation.cpp and EdgesFromPoints__DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix EdgesFromPoints_(NumericMatrix verts, NumericVector howMany, NumericVector origin);

TEST(icosa_deepstate_test,EdgesFromPoints__test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix verts  = RcppDeepState_NumericMatrix();
  std::string verts_t = "/home/akhila/fuzzer_packages/fuzzedpackages/icosa/inst/testfiles/EdgesFromPoints_/AFL_EdgesFromPoints_/afl_inputs/" + std::to_string(t) + "_verts.qs";
  qs::c_qsave(verts,verts_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "verts values: "<< verts << std::endl;
  NumericVector howMany  = RcppDeepState_NumericVector();
  std::string howMany_t = "/home/akhila/fuzzer_packages/fuzzedpackages/icosa/inst/testfiles/EdgesFromPoints_/AFL_EdgesFromPoints_/afl_inputs/" + std::to_string(t) + "_howMany.qs";
  qs::c_qsave(howMany,howMany_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "howMany values: "<< howMany << std::endl;
  NumericVector origin  = RcppDeepState_NumericVector();
  std::string origin_t = "/home/akhila/fuzzer_packages/fuzzedpackages/icosa/inst/testfiles/EdgesFromPoints_/AFL_EdgesFromPoints_/afl_inputs/" + std::to_string(t) + "_origin.qs";
  qs::c_qsave(origin,origin_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "origin values: "<< origin << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    EdgesFromPoints_(verts,howMany,origin);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
