// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// pheno_DeepState_TestHarness_generation.cpp and pheno_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::List pheno(double jd_et, int ipl, int ephe_flag);

TEST(swephR_deepstate_test,pheno_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector jd_et(1);
  jd_et[0]  = RcppDeepState_double();
  std::string jd_et_t = "/home/akhila/fuzzer_packages/fuzzedpackages/swephR/inst/testfiles/pheno/libFuzzer_pheno/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_jd_et.qs";
  qs::c_qsave(jd_et,jd_et_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "jd_et values: "<< jd_et << std::endl;
  IntegerVector ipl(1);
  ipl[0]  = RcppDeepState_int();
  std::string ipl_t = "/home/akhila/fuzzer_packages/fuzzedpackages/swephR/inst/testfiles/pheno/libFuzzer_pheno/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_ipl.qs";
  qs::c_qsave(ipl,ipl_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ipl values: "<< ipl << std::endl;
  IntegerVector ephe_flag(1);
  ephe_flag[0]  = RcppDeepState_int();
  std::string ephe_flag_t = "/home/akhila/fuzzer_packages/fuzzedpackages/swephR/inst/testfiles/pheno/libFuzzer_pheno/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_ephe_flag.qs";
  qs::c_qsave(ephe_flag,ephe_flag_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ephe_flag values: "<< ephe_flag << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    pheno(jd_et[0],ipl[0],ephe_flag[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
