// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// ic0_DeepState_TestHarness_generation.cpp and ic0_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector ic0(NumericVector ptrs, NumericVector inds, NumericVector vals);

TEST(GPvecchia_deepstate_test,ic0_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector ptrs  = RcppDeepState_NumericVector();
  std::string ptrs_t = "/home/akhila/fuzzer_packages/fuzzedpackages/GPvecchia/inst/testfiles/ic0/libFuzzer_ic0/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_ptrs.qs";
  qs::c_qsave(ptrs,ptrs_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ptrs values: "<< ptrs << std::endl;
  NumericVector inds  = RcppDeepState_NumericVector();
  std::string inds_t = "/home/akhila/fuzzer_packages/fuzzedpackages/GPvecchia/inst/testfiles/ic0/libFuzzer_ic0/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_inds.qs";
  qs::c_qsave(inds,inds_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "inds values: "<< inds << std::endl;
  NumericVector vals  = RcppDeepState_NumericVector();
  std::string vals_t = "/home/akhila/fuzzer_packages/fuzzedpackages/GPvecchia/inst/testfiles/ic0/libFuzzer_ic0/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_vals.qs";
  qs::c_qsave(vals,vals_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "vals values: "<< vals << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    ic0(ptrs,inds,vals);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
