// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// EnsRocaCpp_DeepState_TestHarness_generation.cpp and EnsRocaCpp_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector EnsRocaCpp(NumericMatrix ens, NumericMatrix obs);

TEST(easyVerification_deepstate_test,EnsRocaCpp_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix ens  = RcppDeepState_NumericMatrix();
  std::string ens_t = "/home/akhila/fuzzer_packages/fuzzedpackages/easyVerification/inst/testfiles/EnsRocaCpp/AFL_EnsRocaCpp/afl_inputs/" + std::to_string(t) + "_ens.qs";
  qs::c_qsave(ens,ens_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ens values: "<< ens << std::endl;
  NumericMatrix obs  = RcppDeepState_NumericMatrix();
  std::string obs_t = "/home/akhila/fuzzer_packages/fuzzedpackages/easyVerification/inst/testfiles/EnsRocaCpp/AFL_EnsRocaCpp/afl_inputs/" + std::to_string(t) + "_obs.qs";
  qs::c_qsave(obs,obs_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "obs values: "<< obs << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    EnsRocaCpp(ens,obs);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
