// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// indexTranspose_cpp_DeepState_TestHarness_generation.cpp and indexTranspose_cpp_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

IntegerVector indexTranspose_cpp(IntegerVector id, int dim1, int dim2);

TEST(landscapeR_deepstate_test,indexTranspose_cpp_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector id  = RcppDeepState_IntegerVector();
  std::string id_t = "/home/akhila/fuzzer_packages/fuzzedpackages/landscapeR/inst/testfiles/indexTranspose_cpp/libFuzzer_indexTranspose_cpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_id.qs";
  qs::c_qsave(id,id_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "id values: "<< id << std::endl;
  IntegerVector dim1(1);
  dim1[0]  = RcppDeepState_int();
  std::string dim1_t = "/home/akhila/fuzzer_packages/fuzzedpackages/landscapeR/inst/testfiles/indexTranspose_cpp/libFuzzer_indexTranspose_cpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_dim1.qs";
  qs::c_qsave(dim1,dim1_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "dim1 values: "<< dim1 << std::endl;
  IntegerVector dim2(1);
  dim2[0]  = RcppDeepState_int();
  std::string dim2_t = "/home/akhila/fuzzer_packages/fuzzedpackages/landscapeR/inst/testfiles/indexTranspose_cpp/libFuzzer_indexTranspose_cpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_dim2.qs";
  qs::c_qsave(dim2,dim2_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "dim2 values: "<< dim2 << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    indexTranspose_cpp(id,dim1[0],dim2[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
