// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// updateresidual_DeepState_TestHarness_generation.cpp and updateresidual_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

void updateresidual(NumericVector resid, NumericVector y, NumericMatrix thetamat, int j, int n, int p);

TEST(flam_deepstate_test,updateresidual_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector resid  = RcppDeepState_NumericVector();
  std::string resid_t = "/home/akhila/fuzzer_packages/fuzzedpackages/flam/inst/testfiles/updateresidual/AFL_updateresidual/afl_inputs/" + std::to_string(t) + "_resid.qs";
  qs::c_qsave(resid,resid_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "resid values: "<< resid << std::endl;
  NumericVector y  = RcppDeepState_NumericVector();
  std::string y_t = "/home/akhila/fuzzer_packages/fuzzedpackages/flam/inst/testfiles/updateresidual/AFL_updateresidual/afl_inputs/" + std::to_string(t) + "_y.qs";
  qs::c_qsave(y,y_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "y values: "<< y << std::endl;
  NumericMatrix thetamat  = RcppDeepState_NumericMatrix();
  std::string thetamat_t = "/home/akhila/fuzzer_packages/fuzzedpackages/flam/inst/testfiles/updateresidual/AFL_updateresidual/afl_inputs/" + std::to_string(t) + "_thetamat.qs";
  qs::c_qsave(thetamat,thetamat_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "thetamat values: "<< thetamat << std::endl;
  IntegerVector j(1);
  j[0]  = RcppDeepState_int();
  std::string j_t = "/home/akhila/fuzzer_packages/fuzzedpackages/flam/inst/testfiles/updateresidual/AFL_updateresidual/afl_inputs/" + std::to_string(t) + "_j.qs";
  qs::c_qsave(j,j_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "j values: "<< j << std::endl;
  IntegerVector n(1);
  n[0]  = RcppDeepState_int();
  std::string n_t = "/home/akhila/fuzzer_packages/fuzzedpackages/flam/inst/testfiles/updateresidual/AFL_updateresidual/afl_inputs/" + std::to_string(t) + "_n.qs";
  qs::c_qsave(n,n_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "n values: "<< n << std::endl;
  IntegerVector p(1);
  p[0]  = RcppDeepState_int();
  std::string p_t = "/home/akhila/fuzzer_packages/fuzzedpackages/flam/inst/testfiles/updateresidual/AFL_updateresidual/afl_inputs/" + std::to_string(t) + "_p.qs";
  qs::c_qsave(p,p_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "p values: "<< p << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    updateresidual(resid,y,thetamat,j[0],n[0],p[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
