// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// Knotnew_DeepState_TestHarness_generation.cpp and Knotnew_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector Knotnew(NumericVector wht, NumericVector restmp, NumericVector x, NumericVector dcm, NumericVector oldknots, double tol);

TEST(GeDS_deepstate_test,Knotnew_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector wht  = RcppDeepState_NumericVector();
  std::string wht_t = "/home/akhila/fuzzer_packages/fuzzedpackages/GeDS/inst/testfiles/Knotnew/AFL_Knotnew/afl_inputs/" + std::to_string(t) + "_wht.qs";
  qs::c_qsave(wht,wht_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "wht values: "<< wht << std::endl;
  NumericVector restmp  = RcppDeepState_NumericVector();
  std::string restmp_t = "/home/akhila/fuzzer_packages/fuzzedpackages/GeDS/inst/testfiles/Knotnew/AFL_Knotnew/afl_inputs/" + std::to_string(t) + "_restmp.qs";
  qs::c_qsave(restmp,restmp_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "restmp values: "<< restmp << std::endl;
  NumericVector x  = RcppDeepState_NumericVector();
  std::string x_t = "/home/akhila/fuzzer_packages/fuzzedpackages/GeDS/inst/testfiles/Knotnew/AFL_Knotnew/afl_inputs/" + std::to_string(t) + "_x.qs";
  qs::c_qsave(x,x_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  NumericVector dcm  = RcppDeepState_NumericVector();
  std::string dcm_t = "/home/akhila/fuzzer_packages/fuzzedpackages/GeDS/inst/testfiles/Knotnew/AFL_Knotnew/afl_inputs/" + std::to_string(t) + "_dcm.qs";
  qs::c_qsave(dcm,dcm_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "dcm values: "<< dcm << std::endl;
  NumericVector oldknots  = RcppDeepState_NumericVector();
  std::string oldknots_t = "/home/akhila/fuzzer_packages/fuzzedpackages/GeDS/inst/testfiles/Knotnew/AFL_Knotnew/afl_inputs/" + std::to_string(t) + "_oldknots.qs";
  qs::c_qsave(oldknots,oldknots_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "oldknots values: "<< oldknots << std::endl;
  NumericVector tol(1);
  tol[0]  = RcppDeepState_double();
  std::string tol_t = "/home/akhila/fuzzer_packages/fuzzedpackages/GeDS/inst/testfiles/Knotnew/AFL_Knotnew/afl_inputs/" + std::to_string(t) + "_tol.qs";
  qs::c_qsave(tol,tol_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tol values: "<< tol << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    Knotnew(wht,restmp,x,dcm,oldknots,tol[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
