// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// sample_int_replace_DeepState_TestHarness_generation.cpp and sample_int_replace_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

IntegerVector sample_int_replace(NumericVector probabilities, int n);

TEST(xyz_deepstate_test,sample_int_replace_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector probabilities  = RcppDeepState_NumericVector();
  std::string probabilities_t = "/home/akhila/fuzzer_packages/fuzzedpackages/xyz/inst/testfiles/sample_int_replace/libFuzzer_sample_int_replace/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_probabilities.qs";
  qs::c_qsave(probabilities,probabilities_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "probabilities values: "<< probabilities << std::endl;
  IntegerVector n(1);
  n[0]  = RcppDeepState_int();
  std::string n_t = "/home/akhila/fuzzer_packages/fuzzedpackages/xyz/inst/testfiles/sample_int_replace/libFuzzer_sample_int_replace/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_n.qs";
  qs::c_qsave(n,n_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "n values: "<< n << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    sample_int_replace(probabilities,n[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
