// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// xChromosomal_DeepState_TestHarness_generation.cpp and xChromosomal_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double xChromosomal(IntegerVector rmV, IntegerVector mfV, int rk, NumericVector robservedValsV, NumericVector rPvalsV, int rstatID, int rhistobins, NumericVector rhistoboundsV, double rhistoData, int rsafeSecs, double tables);

TEST(HardyWeinberg_deepstate_test,xChromosomal_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector rmV  = RcppDeepState_IntegerVector();
  std::string rmV_t = "/home/akhila/fuzzer_packages/fuzzedpackages/HardyWeinberg/inst/testfiles/xChromosomal/libFuzzer_xChromosomal/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_rmV.qs";
  qs::c_qsave(rmV,rmV_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rmV values: "<< rmV << std::endl;
  IntegerVector mfV  = RcppDeepState_IntegerVector();
  std::string mfV_t = "/home/akhila/fuzzer_packages/fuzzedpackages/HardyWeinberg/inst/testfiles/xChromosomal/libFuzzer_xChromosomal/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_mfV.qs";
  qs::c_qsave(mfV,mfV_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "mfV values: "<< mfV << std::endl;
  IntegerVector rk(1);
  rk[0]  = RcppDeepState_int();
  std::string rk_t = "/home/akhila/fuzzer_packages/fuzzedpackages/HardyWeinberg/inst/testfiles/xChromosomal/libFuzzer_xChromosomal/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_rk.qs";
  qs::c_qsave(rk,rk_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rk values: "<< rk << std::endl;
  NumericVector robservedValsV  = RcppDeepState_NumericVector();
  std::string robservedValsV_t = "/home/akhila/fuzzer_packages/fuzzedpackages/HardyWeinberg/inst/testfiles/xChromosomal/libFuzzer_xChromosomal/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_robservedValsV.qs";
  qs::c_qsave(robservedValsV,robservedValsV_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "robservedValsV values: "<< robservedValsV << std::endl;
  NumericVector rPvalsV  = RcppDeepState_NumericVector();
  std::string rPvalsV_t = "/home/akhila/fuzzer_packages/fuzzedpackages/HardyWeinberg/inst/testfiles/xChromosomal/libFuzzer_xChromosomal/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_rPvalsV.qs";
  qs::c_qsave(rPvalsV,rPvalsV_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rPvalsV values: "<< rPvalsV << std::endl;
  IntegerVector rstatID(1);
  rstatID[0]  = RcppDeepState_int();
  std::string rstatID_t = "/home/akhila/fuzzer_packages/fuzzedpackages/HardyWeinberg/inst/testfiles/xChromosomal/libFuzzer_xChromosomal/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_rstatID.qs";
  qs::c_qsave(rstatID,rstatID_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rstatID values: "<< rstatID << std::endl;
  IntegerVector rhistobins(1);
  rhistobins[0]  = RcppDeepState_int();
  std::string rhistobins_t = "/home/akhila/fuzzer_packages/fuzzedpackages/HardyWeinberg/inst/testfiles/xChromosomal/libFuzzer_xChromosomal/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_rhistobins.qs";
  qs::c_qsave(rhistobins,rhistobins_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rhistobins values: "<< rhistobins << std::endl;
  NumericVector rhistoboundsV  = RcppDeepState_NumericVector();
  std::string rhistoboundsV_t = "/home/akhila/fuzzer_packages/fuzzedpackages/HardyWeinberg/inst/testfiles/xChromosomal/libFuzzer_xChromosomal/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_rhistoboundsV.qs";
  qs::c_qsave(rhistoboundsV,rhistoboundsV_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rhistoboundsV values: "<< rhistoboundsV << std::endl;
  NumericVector rhistoData(1);
  rhistoData[0]  = RcppDeepState_double();
  std::string rhistoData_t = "/home/akhila/fuzzer_packages/fuzzedpackages/HardyWeinberg/inst/testfiles/xChromosomal/libFuzzer_xChromosomal/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_rhistoData.qs";
  qs::c_qsave(rhistoData,rhistoData_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rhistoData values: "<< rhistoData << std::endl;
  IntegerVector rsafeSecs(1);
  rsafeSecs[0]  = RcppDeepState_int();
  std::string rsafeSecs_t = "/home/akhila/fuzzer_packages/fuzzedpackages/HardyWeinberg/inst/testfiles/xChromosomal/libFuzzer_xChromosomal/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_rsafeSecs.qs";
  qs::c_qsave(rsafeSecs,rsafeSecs_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rsafeSecs values: "<< rsafeSecs << std::endl;
  NumericVector tables(1);
  tables[0]  = RcppDeepState_double();
  std::string tables_t = "/home/akhila/fuzzer_packages/fuzzedpackages/HardyWeinberg/inst/testfiles/xChromosomal/libFuzzer_xChromosomal/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_tables.qs";
  qs::c_qsave(tables,tables_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tables values: "<< tables << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    xChromosomal(rmV,mfV,rk[0],robservedValsV,rPvalsV,rstatID[0],rhistobins[0],rhistoboundsV,rhistoData[0],rsafeSecs[0],tables[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
