// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// InverseWeightByFaceCenter__DeepState_TestHarness_generation.cpp and InverseWeightByFaceCenter__DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector InverseWeightByFaceCenter_(NumericMatrix fcNew, NumericVector loc, NumericMatrix n, NumericMatrix fcOld, NumericVector values, NumericVector origin, int deg);

TEST(icosa_deepstate_test,InverseWeightByFaceCenter__test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix fcNew  = RcppDeepState_NumericMatrix();
  std::string fcNew_t = "/home/akhila/fuzzer_packages/fuzzedpackages/icosa/inst/testfiles/InverseWeightByFaceCenter_/libFuzzer_InverseWeightByFaceCenter_/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_fcNew.qs";
  qs::c_qsave(fcNew,fcNew_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "fcNew values: "<< fcNew << std::endl;
  NumericVector loc  = RcppDeepState_NumericVector();
  std::string loc_t = "/home/akhila/fuzzer_packages/fuzzedpackages/icosa/inst/testfiles/InverseWeightByFaceCenter_/libFuzzer_InverseWeightByFaceCenter_/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_loc.qs";
  qs::c_qsave(loc,loc_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "loc values: "<< loc << std::endl;
  NumericMatrix n  = RcppDeepState_NumericMatrix();
  std::string n_t = "/home/akhila/fuzzer_packages/fuzzedpackages/icosa/inst/testfiles/InverseWeightByFaceCenter_/libFuzzer_InverseWeightByFaceCenter_/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_n.qs";
  qs::c_qsave(n,n_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "n values: "<< n << std::endl;
  NumericMatrix fcOld  = RcppDeepState_NumericMatrix();
  std::string fcOld_t = "/home/akhila/fuzzer_packages/fuzzedpackages/icosa/inst/testfiles/InverseWeightByFaceCenter_/libFuzzer_InverseWeightByFaceCenter_/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_fcOld.qs";
  qs::c_qsave(fcOld,fcOld_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "fcOld values: "<< fcOld << std::endl;
  NumericVector values  = RcppDeepState_NumericVector();
  std::string values_t = "/home/akhila/fuzzer_packages/fuzzedpackages/icosa/inst/testfiles/InverseWeightByFaceCenter_/libFuzzer_InverseWeightByFaceCenter_/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_values.qs";
  qs::c_qsave(values,values_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "values values: "<< values << std::endl;
  NumericVector origin  = RcppDeepState_NumericVector();
  std::string origin_t = "/home/akhila/fuzzer_packages/fuzzedpackages/icosa/inst/testfiles/InverseWeightByFaceCenter_/libFuzzer_InverseWeightByFaceCenter_/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_origin.qs";
  qs::c_qsave(origin,origin_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "origin values: "<< origin << std::endl;
  IntegerVector deg(1);
  deg[0]  = RcppDeepState_int();
  std::string deg_t = "/home/akhila/fuzzer_packages/fuzzedpackages/icosa/inst/testfiles/InverseWeightByFaceCenter_/libFuzzer_InverseWeightByFaceCenter_/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_deg.qs";
  qs::c_qsave(deg,deg_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "deg values: "<< deg << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    InverseWeightByFaceCenter_(fcNew,loc,n,fcOld,values,origin,deg[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
