# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

OrderKmeansCpp <- function(x, K = 4L, num_init = 10L) {
    .Call('_offlineChange_OrderKmeansCpp', PACKAGE = 'offlineChange', x, K, num_init)
}

PriorRangeOrderKmeansCpp <- function(x, prior_range_x, num_init = 10L) {
    .Call('_offlineChange_PriorRangeOrderKmeansCpp', PACKAGE = 'offlineChange', x, prior_range_x, num_init)
}

