// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// extractMandatory_DeepState_TestHarness_generation.cpp and extractMandatory_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List extractMandatory(CharacterVector x, CharacterVector command, int nCommands);

TEST(hutilscpp_deepstate_test,extractMandatory_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  CharacterVector x  = RcppDeepState_CharacterVector();
  std::string x_t = "/home/akhila/fuzzer_packages/fuzzedpackages/hutilscpp/inst/testfiles/extractMandatory/libFuzzer_extractMandatory/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_x.qs";
  qs::c_qsave(x,x_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  CharacterVector command  = RcppDeepState_CharacterVector();
  std::string command_t = "/home/akhila/fuzzer_packages/fuzzedpackages/hutilscpp/inst/testfiles/extractMandatory/libFuzzer_extractMandatory/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_command.qs";
  qs::c_qsave(command,command_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "command values: "<< command << std::endl;
  IntegerVector nCommands(1);
  nCommands[0]  = RcppDeepState_int();
  std::string nCommands_t = "/home/akhila/fuzzer_packages/fuzzedpackages/hutilscpp/inst/testfiles/extractMandatory/libFuzzer_extractMandatory/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_nCommands.qs";
  qs::c_qsave(nCommands,nCommands_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nCommands values: "<< nCommands << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    extractMandatory(x,command,nCommands[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
