// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// which_index_DeepState_TestHarness_generation.cpp and which_index_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

int which_index(IntegerVector indices, IntegerVector m);

TEST(Quartet_deepstate_test,which_index_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector indices  = RcppDeepState_IntegerVector();
  std::string indices_t = "/home/akhila/fuzzer_packages/fuzzedpackages/Quartet/inst/testfiles/which_index/AFL_which_index/afl_inputs/" + std::to_string(t) + "_indices.qs";
  qs::c_qsave(indices,indices_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "indices values: "<< indices << std::endl;
  IntegerVector m  = RcppDeepState_IntegerVector();
  std::string m_t = "/home/akhila/fuzzer_packages/fuzzedpackages/Quartet/inst/testfiles/which_index/AFL_which_index/afl_inputs/" + std::to_string(t) + "_m.qs";
  qs::c_qsave(m,m_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "m values: "<< m << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    which_index(indices,m);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
