// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// prims_DeepState_TestHarness_generation.cpp and prims_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix prims(const NumericVector x_dist, const int n);

TEST(dbscan_deepstate_test,prims_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector x_dist  = RcppDeepState_NumericVector();
  std::string x_dist_t = "/home/akhila/fuzzer_packages/fuzzedpackages/dbscan/inst/testfiles/prims/libFuzzer_prims/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_x_dist.qs";
  qs::c_qsave(x_dist,x_dist_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x_dist values: "<< x_dist << std::endl;
  IntegerVector n(1);
  n[0]  = RcppDeepState_int();
  std::string n_t = "/home/akhila/fuzzer_packages/fuzzedpackages/dbscan/inst/testfiles/prims/libFuzzer_prims/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_n.qs";
  qs::c_qsave(n,n_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "n values: "<< n << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    prims(x_dist,n[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
