// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// mfwrapper_DeepState_TestHarness_generation.cpp and mfwrapper_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List mfwrapper(NumericMatrix xi, IntegerVector weights, NumericMatrix qJ, IntegerVector Lv, NumericVector Eps, NumericVector priorCount);

TEST(bbl_deepstate_test,mfwrapper_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix xi  = RcppDeepState_NumericMatrix();
  std::string xi_t = "/home/akhila/fuzzer_packages/fuzzedpackages/bbl/inst/testfiles/mfwrapper/libFuzzer_mfwrapper/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_xi.qs";
  qs::c_qsave(xi,xi_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "xi values: "<< xi << std::endl;
  IntegerVector weights  = RcppDeepState_IntegerVector();
  std::string weights_t = "/home/akhila/fuzzer_packages/fuzzedpackages/bbl/inst/testfiles/mfwrapper/libFuzzer_mfwrapper/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_weights.qs";
  qs::c_qsave(weights,weights_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "weights values: "<< weights << std::endl;
  NumericMatrix qJ  = RcppDeepState_NumericMatrix();
  std::string qJ_t = "/home/akhila/fuzzer_packages/fuzzedpackages/bbl/inst/testfiles/mfwrapper/libFuzzer_mfwrapper/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_qJ.qs";
  qs::c_qsave(qJ,qJ_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "qJ values: "<< qJ << std::endl;
  IntegerVector Lv  = RcppDeepState_IntegerVector();
  std::string Lv_t = "/home/akhila/fuzzer_packages/fuzzedpackages/bbl/inst/testfiles/mfwrapper/libFuzzer_mfwrapper/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_Lv.qs";
  qs::c_qsave(Lv,Lv_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Lv values: "<< Lv << std::endl;
  NumericVector Eps  = RcppDeepState_NumericVector();
  std::string Eps_t = "/home/akhila/fuzzer_packages/fuzzedpackages/bbl/inst/testfiles/mfwrapper/libFuzzer_mfwrapper/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_Eps.qs";
  qs::c_qsave(Eps,Eps_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Eps values: "<< Eps << std::endl;
  NumericVector priorCount  = RcppDeepState_NumericVector();
  std::string priorCount_t = "/home/akhila/fuzzer_packages/fuzzedpackages/bbl/inst/testfiles/mfwrapper/libFuzzer_mfwrapper/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_priorCount.qs";
  qs::c_qsave(priorCount,priorCount_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "priorCount values: "<< priorCount << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    mfwrapper(xi,weights,qJ,Lv,Eps,priorCount);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
