// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// buildCellList_DeepState_TestHarness_generation.cpp and buildCellList_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List buildCellList(CharacterVector r, CharacterVector t, CharacterVector v);

TEST(openxlsx_deepstate_test,buildCellList_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  CharacterVector r  = RcppDeepState_CharacterVector();
  std::string r_t = "/home/akhila/fuzzer_packages/fuzzedpackages/openxlsx/inst/testfiles/buildCellList/libFuzzer_buildCellList/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_r.qs";
  qs::c_qsave(r,r_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "r values: "<< r << std::endl;
  CharacterVector t  = RcppDeepState_CharacterVector();
  std::string t_t = "/home/akhila/fuzzer_packages/fuzzedpackages/openxlsx/inst/testfiles/buildCellList/libFuzzer_buildCellList/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_t.qs";
  qs::c_qsave(t,t_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "t values: "<< t << std::endl;
  CharacterVector v  = RcppDeepState_CharacterVector();
  std::string v_t = "/home/akhila/fuzzer_packages/fuzzedpackages/openxlsx/inst/testfiles/buildCellList/libFuzzer_buildCellList/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_v.qs";
  qs::c_qsave(v,v_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "v values: "<< v << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    buildCellList(r,t,v);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
