// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// pheno_ut_DeepState_TestHarness_generation.cpp and pheno_ut_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::List pheno_ut(double jd_ut, int ipl, int ephe_flag);

TEST(swephR_deepstate_test,pheno_ut_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector jd_ut(1);
  jd_ut[0]  = RcppDeepState_double();
  std::string jd_ut_t = "/home/akhila/fuzzer_packages/fuzzedpackages/swephR/inst/testfiles/pheno_ut/AFL_pheno_ut/afl_inputs/" + std::to_string(t) + "_jd_ut.qs";
  qs::c_qsave(jd_ut,jd_ut_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "jd_ut values: "<< jd_ut << std::endl;
  IntegerVector ipl(1);
  ipl[0]  = RcppDeepState_int();
  std::string ipl_t = "/home/akhila/fuzzer_packages/fuzzedpackages/swephR/inst/testfiles/pheno_ut/AFL_pheno_ut/afl_inputs/" + std::to_string(t) + "_ipl.qs";
  qs::c_qsave(ipl,ipl_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ipl values: "<< ipl << std::endl;
  IntegerVector ephe_flag(1);
  ephe_flag[0]  = RcppDeepState_int();
  std::string ephe_flag_t = "/home/akhila/fuzzer_packages/fuzzedpackages/swephR/inst/testfiles/pheno_ut/AFL_pheno_ut/afl_inputs/" + std::to_string(t) + "_ephe_flag.qs";
  qs::c_qsave(ephe_flag,ephe_flag_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ephe_flag values: "<< ephe_flag << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    pheno_ut(jd_ut[0],ipl[0],ephe_flag[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
