// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// remove_curr_col_DeepState_TestHarness_generation.cpp and remove_curr_col_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix remove_curr_col(NumericMatrix predy, int i);

TEST(bartBMA_deepstate_test,remove_curr_col_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix predy  = RcppDeepState_NumericMatrix();
  std::string predy_t = "/home/akhila/fuzzer_packages/fuzzedpackages/bartBMA/inst/testfiles/remove_curr_col/libFuzzer_remove_curr_col/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_predy.qs";
  qs::c_qsave(predy,predy_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "predy values: "<< predy << std::endl;
  IntegerVector i(1);
  i[0]  = RcppDeepState_int();
  std::string i_t = "/home/akhila/fuzzer_packages/fuzzedpackages/bartBMA/inst/testfiles/remove_curr_col/libFuzzer_remove_curr_col/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_i.qs";
  qs::c_qsave(i,i_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "i values: "<< i << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    remove_curr_col(predy,i[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
