// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// extract_patches_DeepState_TestHarness_generation.cpp and extract_patches_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List extract_patches(NumericVector im, IntegerVector cx, IntegerVector cy, IntegerVector wx, IntegerVector wy, int boundary_conditions);

TEST(imager_deepstate_test,extract_patches_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector im  = RcppDeepState_NumericVector();
  std::string im_t = "/home/akhila/fuzzer_packages/fuzzedpackages/imager/inst/testfiles/extract_patches/libFuzzer_extract_patches/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_im.qs";
  qs::c_qsave(im,im_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "im values: "<< im << std::endl;
  IntegerVector cx  = RcppDeepState_IntegerVector();
  std::string cx_t = "/home/akhila/fuzzer_packages/fuzzedpackages/imager/inst/testfiles/extract_patches/libFuzzer_extract_patches/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_cx.qs";
  qs::c_qsave(cx,cx_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "cx values: "<< cx << std::endl;
  IntegerVector cy  = RcppDeepState_IntegerVector();
  std::string cy_t = "/home/akhila/fuzzer_packages/fuzzedpackages/imager/inst/testfiles/extract_patches/libFuzzer_extract_patches/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_cy.qs";
  qs::c_qsave(cy,cy_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "cy values: "<< cy << std::endl;
  IntegerVector wx  = RcppDeepState_IntegerVector();
  std::string wx_t = "/home/akhila/fuzzer_packages/fuzzedpackages/imager/inst/testfiles/extract_patches/libFuzzer_extract_patches/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_wx.qs";
  qs::c_qsave(wx,wx_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "wx values: "<< wx << std::endl;
  IntegerVector wy  = RcppDeepState_IntegerVector();
  std::string wy_t = "/home/akhila/fuzzer_packages/fuzzedpackages/imager/inst/testfiles/extract_patches/libFuzzer_extract_patches/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_wy.qs";
  qs::c_qsave(wy,wy_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "wy values: "<< wy << std::endl;
  IntegerVector boundary_conditions(1);
  boundary_conditions[0]  = RcppDeepState_int();
  std::string boundary_conditions_t = "/home/akhila/fuzzer_packages/fuzzedpackages/imager/inst/testfiles/extract_patches/libFuzzer_extract_patches/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_boundary_conditions.qs";
  qs::c_qsave(boundary_conditions,boundary_conditions_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "boundary_conditions values: "<< boundary_conditions << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    extract_patches(im,cx,cy,wx,wy,boundary_conditions[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
