// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// scale_intr_DeepState_TestHarness_generation.cpp and scale_intr_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector scale_intr(NumericMatrix X, int pair_x, int pair_y);

TEST(xyz_deepstate_test,scale_intr_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix X  = RcppDeepState_NumericMatrix();
  std::string X_t = "/home/akhila/fuzzer_packages/fuzzedpackages/xyz/inst/testfiles/scale_intr/libFuzzer_scale_intr/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_X.qs";
  qs::c_qsave(X,X_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "X values: "<< X << std::endl;
  IntegerVector pair_x(1);
  pair_x[0]  = RcppDeepState_int();
  std::string pair_x_t = "/home/akhila/fuzzer_packages/fuzzedpackages/xyz/inst/testfiles/scale_intr/libFuzzer_scale_intr/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_pair_x.qs";
  qs::c_qsave(pair_x,pair_x_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "pair_x values: "<< pair_x << std::endl;
  IntegerVector pair_y(1);
  pair_y[0]  = RcppDeepState_int();
  std::string pair_y_t = "/home/akhila/fuzzer_packages/fuzzedpackages/xyz/inst/testfiles/scale_intr/libFuzzer_scale_intr/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_pair_y.qs";
  qs::c_qsave(pair_y,pair_y_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "pair_y values: "<< pair_y << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    scale_intr(X,pair_x[0],pair_y[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
