// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// roll_median_numeric_vector_DeepState_TestHarness_generation.cpp and roll_median_numeric_vector_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector roll_median_numeric_vector(NumericVector x, int n, int increment);

TEST(seismicRoll_deepstate_test,roll_median_numeric_vector_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector x  = RcppDeepState_NumericVector();
  std::string x_t = "/home/akhila/fuzzer_packages/fuzzedpackages/seismicRoll/inst/testfiles/roll_median_numeric_vector/libFuzzer_roll_median_numeric_vector/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_x.qs";
  qs::c_qsave(x,x_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  IntegerVector n(1);
  n[0]  = RcppDeepState_int();
  std::string n_t = "/home/akhila/fuzzer_packages/fuzzedpackages/seismicRoll/inst/testfiles/roll_median_numeric_vector/libFuzzer_roll_median_numeric_vector/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_n.qs";
  qs::c_qsave(n,n_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "n values: "<< n << std::endl;
  IntegerVector increment(1);
  increment[0]  = RcppDeepState_int();
  std::string increment_t = "/home/akhila/fuzzer_packages/fuzzedpackages/seismicRoll/inst/testfiles/roll_median_numeric_vector/libFuzzer_roll_median_numeric_vector/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_increment.qs";
  qs::c_qsave(increment,increment_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "increment values: "<< increment << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    roll_median_numeric_vector(x,n[0],increment[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
