# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lbNumeric <- function(sortedValues, valueToSearch) {
    .Call(`_bsearchtools_lbNumeric`, sortedValues, valueToSearch)
}

ubNumeric <- function(sortedValues, valueToSearch) {
    .Call(`_bsearchtools_ubNumeric`, sortedValues, valueToSearch)
}

indexesInRangeNumeric <- function(sortedValues, lbInclusive, ubInclusive, indexesRemap = NULL) {
    .Call(`_bsearchtools_indexesInRangeNumeric`, sortedValues, lbInclusive, ubInclusive, indexesRemap)
}

indexesEqualToNumeric <- function(sortedValues, valueToSearch, indexesRemap = NULL) {
    .Call(`_bsearchtools_indexesEqualToNumeric`, sortedValues, valueToSearch, indexesRemap)
}

lbInteger <- function(sortedValues, valueToSearch) {
    .Call(`_bsearchtools_lbInteger`, sortedValues, valueToSearch)
}

ubInteger <- function(sortedValues, valueToSearch) {
    .Call(`_bsearchtools_ubInteger`, sortedValues, valueToSearch)
}

indexesInRangeInteger <- function(sortedValues, lbInclusive, ubInclusive, indexesRemap = NULL) {
    .Call(`_bsearchtools_indexesInRangeInteger`, sortedValues, lbInclusive, ubInclusive, indexesRemap)
}

indexesEqualToInteger <- function(sortedValues, valueToSearch, indexesRemap = NULL) {
    .Call(`_bsearchtools_indexesEqualToInteger`, sortedValues, valueToSearch, indexesRemap)
}

lbCharacter <- function(sortedValues, valueToSearch) {
    .Call(`_bsearchtools_lbCharacter`, sortedValues, valueToSearch)
}

ubCharacter <- function(sortedValues, valueToSearch) {
    .Call(`_bsearchtools_ubCharacter`, sortedValues, valueToSearch)
}

indexesInRangeCharacter <- function(sortedValues, lbInclusive, ubInclusive, indexesRemap = NULL) {
    .Call(`_bsearchtools_indexesInRangeCharacter`, sortedValues, lbInclusive, ubInclusive, indexesRemap)
}

indexesEqualToCharacter <- function(sortedValues, valueToSearch, indexesRemap = NULL) {
    .Call(`_bsearchtools_indexesEqualToCharacter`, sortedValues, valueToSearch, indexesRemap)
}

lbLogical <- function(sortedValues, valueToSearch) {
    .Call(`_bsearchtools_lbLogical`, sortedValues, valueToSearch)
}

ubLogical <- function(sortedValues, valueToSearch) {
    .Call(`_bsearchtools_ubLogical`, sortedValues, valueToSearch)
}

indexesInRangeLogical <- function(sortedValues, lbInclusive, ubInclusive, indexesRemap = NULL) {
    .Call(`_bsearchtools_indexesInRangeLogical`, sortedValues, lbInclusive, ubInclusive, indexesRemap)
}

indexesEqualToLogical <- function(sortedValues, valueToSearch, indexesRemap = NULL) {
    .Call(`_bsearchtools_indexesEqualToLogical`, sortedValues, valueToSearch, indexesRemap)
}

lb <- function(sortedValues, valueToSearch) {
    .Call(`_bsearchtools_lb`, sortedValues, valueToSearch)
}

ub <- function(sortedValues, valueToSearch) {
    .Call(`_bsearchtools_ub`, sortedValues, valueToSearch)
}

indexesInRange <- function(sortedValues, lbInclusive, ubInclusive, indexesRemap = NULL) {
    .Call(`_bsearchtools_indexesInRange`, sortedValues, lbInclusive, ubInclusive, indexesRemap)
}

indexesEqualTo <- function(sortedValues, valueToSearch, indexesRemap = NULL) {
    .Call(`_bsearchtools_indexesEqualTo`, sortedValues, valueToSearch, indexesRemap)
}

.intersectInteger <- function(x, y) {
    .Call(`_bsearchtools_intersectInteger`, x, y)
}

.unionInteger <- function(vec1, vec2) {
    .Call(`_bsearchtools_unionInteger`, vec1, vec2)
}

.unionIntegerList <- function(list) {
    .Call(`_bsearchtools_unionIntegerList`, list)
}

