// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// set_cimg_omp_DeepState_TestHarness_generation.cpp and set_cimg_omp_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

int set_cimg_omp(int mode);

TEST(imager_deepstate_test,set_cimg_omp_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector mode(1);
  mode[0]  = RcppDeepState_int();
  std::string mode_t = "/home/akhila/fuzzer_packages/fuzzedpackages/imager/inst/testfiles/set_cimg_omp/AFL_set_cimg_omp/afl_inputs/" + std::to_string(t) + "_mode.qs";
  qs::c_qsave(mode,mode_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "mode values: "<< mode << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    set_cimg_omp(mode[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
