// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// gset_raw_DeepState_TestHarness_generation.cpp and gset_raw_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double gset_raw(int N, IntegerVector S, NumericVector r, int min_its, int max_its, double signif, double log_dismiss);

TEST(gsEasy_deepstate_test,gset_raw_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector N(1);
  N[0]  = RcppDeepState_int();
  std::string N_t = "/home/akhila/fuzzer_packages/fuzzedpackages/gsEasy/inst/testfiles/gset_raw/libFuzzer_gset_raw/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_N.qs";
  qs::c_qsave(N,N_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "N values: "<< N << std::endl;
  IntegerVector S  = RcppDeepState_IntegerVector();
  std::string S_t = "/home/akhila/fuzzer_packages/fuzzedpackages/gsEasy/inst/testfiles/gset_raw/libFuzzer_gset_raw/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_S.qs";
  qs::c_qsave(S,S_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "S values: "<< S << std::endl;
  NumericVector r  = RcppDeepState_NumericVector();
  std::string r_t = "/home/akhila/fuzzer_packages/fuzzedpackages/gsEasy/inst/testfiles/gset_raw/libFuzzer_gset_raw/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_r.qs";
  qs::c_qsave(r,r_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "r values: "<< r << std::endl;
  IntegerVector min_its(1);
  min_its[0]  = RcppDeepState_int();
  std::string min_its_t = "/home/akhila/fuzzer_packages/fuzzedpackages/gsEasy/inst/testfiles/gset_raw/libFuzzer_gset_raw/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_min_its.qs";
  qs::c_qsave(min_its,min_its_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "min_its values: "<< min_its << std::endl;
  IntegerVector max_its(1);
  max_its[0]  = RcppDeepState_int();
  std::string max_its_t = "/home/akhila/fuzzer_packages/fuzzedpackages/gsEasy/inst/testfiles/gset_raw/libFuzzer_gset_raw/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_max_its.qs";
  qs::c_qsave(max_its,max_its_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "max_its values: "<< max_its << std::endl;
  NumericVector signif(1);
  signif[0]  = RcppDeepState_double();
  std::string signif_t = "/home/akhila/fuzzer_packages/fuzzedpackages/gsEasy/inst/testfiles/gset_raw/libFuzzer_gset_raw/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_signif.qs";
  qs::c_qsave(signif,signif_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "signif values: "<< signif << std::endl;
  NumericVector log_dismiss(1);
  log_dismiss[0]  = RcppDeepState_double();
  std::string log_dismiss_t = "/home/akhila/fuzzer_packages/fuzzedpackages/gsEasy/inst/testfiles/gset_raw/libFuzzer_gset_raw/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_log_dismiss.qs";
  qs::c_qsave(log_dismiss,log_dismiss_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "log_dismiss values: "<< log_dismiss << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    gset_raw(N[0],S,r,min_its[0],max_its[0],signif[0],log_dismiss[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
