// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// convertVtoTheta_DeepState_TestHarness_generation.cpp and convertVtoTheta_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix convertVtoTheta(NumericMatrix vmat, NumericVector prod);

TEST(Rlda_deepstate_test,convertVtoTheta_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix vmat  = RcppDeepState_NumericMatrix();
  std::string vmat_t = "/home/akhila/fuzzer_packages/fuzzedpackages/Rlda/inst/testfiles/convertVtoTheta/libFuzzer_convertVtoTheta/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_vmat.qs";
  qs::c_qsave(vmat,vmat_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "vmat values: "<< vmat << std::endl;
  NumericVector prod  = RcppDeepState_NumericVector();
  std::string prod_t = "/home/akhila/fuzzer_packages/fuzzedpackages/Rlda/inst/testfiles/convertVtoTheta/libFuzzer_convertVtoTheta/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_prod.qs";
  qs::c_qsave(prod,prod_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "prod values: "<< prod << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    convertVtoTheta(vmat,prod);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
