// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// effectiveSampleSize_DeepState_TestHarness_generation.cpp and effectiveSampleSize_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double effectiveSampleSize(NumericVector log_weights);

TEST(serrsBayes_deepstate_test,effectiveSampleSize_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector log_weights  = RcppDeepState_NumericVector();
  std::string log_weights_t = "/home/akhila/fuzzer_packages/fuzzedpackages/serrsBayes/inst/testfiles/effectiveSampleSize/libFuzzer_effectiveSampleSize/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_log_weights.qs";
  qs::c_qsave(log_weights,log_weights_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "log_weights values: "<< log_weights << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    effectiveSampleSize(log_weights);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
