// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// DirectNeighboursTri__DeepState_TestHarness_generation.cpp and DirectNeighboursTri__DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix DirectNeighboursTri_(NumericMatrix faces);

TEST(icosa_deepstate_test,DirectNeighboursTri__test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix faces  = RcppDeepState_NumericMatrix();
  std::string faces_t = "/home/akhila/fuzzer_packages/fuzzedpackages/icosa/inst/testfiles/DirectNeighboursTri_/AFL_DirectNeighboursTri_/afl_inputs/" + std::to_string(t) + "_faces.qs";
  qs::c_qsave(faces,faces_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "faces values: "<< faces << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    DirectNeighboursTri_(faces);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
