// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// fill_vec_DeepState_TestHarness_generation.cpp and fill_vec_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector fill_vec(NumericVector read_vec, NumericVector read_indices);

TEST(immunarch_deepstate_test,fill_vec_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector read_vec  = RcppDeepState_NumericVector();
  std::string read_vec_t = "/home/akhila/fuzzer_packages/fuzzedpackages/immunarch/inst/testfiles/fill_vec/AFL_fill_vec/afl_inputs/" + std::to_string(t) + "_read_vec.qs";
  qs::c_qsave(read_vec,read_vec_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "read_vec values: "<< read_vec << std::endl;
  NumericVector read_indices  = RcppDeepState_NumericVector();
  std::string read_indices_t = "/home/akhila/fuzzer_packages/fuzzedpackages/immunarch/inst/testfiles/fill_vec/AFL_fill_vec/afl_inputs/" + std::to_string(t) + "_read_indices.qs";
  qs::c_qsave(read_indices,read_indices_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "read_indices values: "<< read_indices << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    fill_vec(read_vec,read_indices);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
