// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// normalise2d_DeepState_TestHarness_generation.cpp and normalise2d_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

arma::mat normalise2d(NumericMatrix mat, const int pnorm, const int axis);

TEST(superml_deepstate_test,normalise2d_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix mat  = RcppDeepState_NumericMatrix();
  std::string mat_t = "/home/akhila/fuzzer_packages/fuzzedpackages/superml/inst/testfiles/normalise2d/AFL_normalise2d/afl_inputs/" + std::to_string(t) + "_mat.qs";
  qs::c_qsave(mat,mat_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "mat values: "<< mat << std::endl;
  IntegerVector pnorm(1);
  pnorm[0]  = RcppDeepState_int();
  std::string pnorm_t = "/home/akhila/fuzzer_packages/fuzzedpackages/superml/inst/testfiles/normalise2d/AFL_normalise2d/afl_inputs/" + std::to_string(t) + "_pnorm.qs";
  qs::c_qsave(pnorm,pnorm_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "pnorm values: "<< pnorm << std::endl;
  IntegerVector axis(1);
  axis[0]  = RcppDeepState_int();
  std::string axis_t = "/home/akhila/fuzzer_packages/fuzzedpackages/superml/inst/testfiles/normalise2d/AFL_normalise2d/afl_inputs/" + std::to_string(t) + "_axis.qs";
  qs::c_qsave(axis,axis_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "axis values: "<< axis << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    normalise2d(mat,pnorm[0],axis[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
