// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// cpp_diag_XUtX_DeepState_TestHarness_generation.cpp and cpp_diag_XUtX_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector cpp_diag_XUtX(NumericMatrix X, NumericMatrix U);

TEST(fixest_deepstate_test,cpp_diag_XUtX_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix X  = RcppDeepState_NumericMatrix();
  std::string X_t = "/home/akhila/fuzzer_packages/fuzzedpackages/fixest/inst/testfiles/cpp_diag_XUtX/AFL_cpp_diag_XUtX/afl_inputs/" + std::to_string(t) + "_X.qs";
  qs::c_qsave(X,X_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "X values: "<< X << std::endl;
  NumericMatrix U  = RcppDeepState_NumericMatrix();
  std::string U_t = "/home/akhila/fuzzer_packages/fuzzedpackages/fixest/inst/testfiles/cpp_diag_XUtX/AFL_cpp_diag_XUtX/afl_inputs/" + std::to_string(t) + "_U.qs";
  qs::c_qsave(U,U_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "U values: "<< U << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    cpp_diag_XUtX(X,U);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
