// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// julday_DeepState_TestHarness_generation.cpp and julday_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double julday(int year, int month, int day, double hourd, int gregflag);

TEST(swephR_deepstate_test,julday_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector year(1);
  year[0]  = RcppDeepState_int();
  std::string year_t = "/home/akhila/fuzzer_packages/fuzzedpackages/swephR/inst/testfiles/julday/AFL_julday/afl_inputs/" + std::to_string(t) + "_year.qs";
  qs::c_qsave(year,year_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "year values: "<< year << std::endl;
  IntegerVector month(1);
  month[0]  = RcppDeepState_int();
  std::string month_t = "/home/akhila/fuzzer_packages/fuzzedpackages/swephR/inst/testfiles/julday/AFL_julday/afl_inputs/" + std::to_string(t) + "_month.qs";
  qs::c_qsave(month,month_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "month values: "<< month << std::endl;
  IntegerVector day(1);
  day[0]  = RcppDeepState_int();
  std::string day_t = "/home/akhila/fuzzer_packages/fuzzedpackages/swephR/inst/testfiles/julday/AFL_julday/afl_inputs/" + std::to_string(t) + "_day.qs";
  qs::c_qsave(day,day_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "day values: "<< day << std::endl;
  NumericVector hourd(1);
  hourd[0]  = RcppDeepState_double();
  std::string hourd_t = "/home/akhila/fuzzer_packages/fuzzedpackages/swephR/inst/testfiles/julday/AFL_julday/afl_inputs/" + std::to_string(t) + "_hourd.qs";
  qs::c_qsave(hourd,hourd_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "hourd values: "<< hourd << std::endl;
  IntegerVector gregflag(1);
  gregflag[0]  = RcppDeepState_int();
  std::string gregflag_t = "/home/akhila/fuzzer_packages/fuzzedpackages/swephR/inst/testfiles/julday/AFL_julday/afl_inputs/" + std::to_string(t) + "_gregflag.qs";
  qs::c_qsave(gregflag,gregflag_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "gregflag values: "<< gregflag << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    julday(year[0],month[0],day[0],hourd[0],gregflag[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
