// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// s2_lnglat_from_numeric_DeepState_TestHarness_generation.cpp and s2_lnglat_from_numeric_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List s2_lnglat_from_numeric(NumericVector lng, NumericVector lat);

TEST(s2_deepstate_test,s2_lnglat_from_numeric_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector lng  = RcppDeepState_NumericVector();
  std::string lng_t = "/home/akhila/fuzzer_packages/fuzzedpackages/s2/inst/testfiles/s2_lnglat_from_numeric/libFuzzer_s2_lnglat_from_numeric/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_lng.qs";
  qs::c_qsave(lng,lng_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "lng values: "<< lng << std::endl;
  NumericVector lat  = RcppDeepState_NumericVector();
  std::string lat_t = "/home/akhila/fuzzer_packages/fuzzedpackages/s2/inst/testfiles/s2_lnglat_from_numeric/libFuzzer_s2_lnglat_from_numeric/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_lat.qs";
  qs::c_qsave(lat,lat_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "lat values: "<< lat << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    s2_lnglat_from_numeric(lng,lat);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
