// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// remove_zero_DeepState_TestHarness_generation.cpp and remove_zero_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector remove_zero(NumericVector nodes_at_depth);

TEST(bartBMA_deepstate_test,remove_zero_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector nodes_at_depth  = RcppDeepState_NumericVector();
  std::string nodes_at_depth_t = "/home/akhila/fuzzer_packages/fuzzedpackages/bartBMA/inst/testfiles/remove_zero/libFuzzer_remove_zero/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_nodes_at_depth.qs";
  qs::c_qsave(nodes_at_depth,nodes_at_depth_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nodes_at_depth values: "<< nodes_at_depth << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    remove_zero(nodes_at_depth);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
