// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// hwe_frequencies_DeepState_TestHarness_generation.cpp and hwe_frequencies_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List hwe_frequencies(IntegerVector allele1, IntegerVector allele2, int min_alleles);

TEST(MESS_deepstate_test,hwe_frequencies_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector allele1  = RcppDeepState_IntegerVector();
  std::string allele1_t = "/home/akhila/fuzzer_packages/fuzzedpackages/MESS/inst/testfiles/hwe_frequencies/libFuzzer_hwe_frequencies/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_allele1.qs";
  qs::c_qsave(allele1,allele1_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "allele1 values: "<< allele1 << std::endl;
  IntegerVector allele2  = RcppDeepState_IntegerVector();
  std::string allele2_t = "/home/akhila/fuzzer_packages/fuzzedpackages/MESS/inst/testfiles/hwe_frequencies/libFuzzer_hwe_frequencies/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_allele2.qs";
  qs::c_qsave(allele2,allele2_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "allele2 values: "<< allele2 << std::endl;
  IntegerVector min_alleles(1);
  min_alleles[0]  = RcppDeepState_int();
  std::string min_alleles_t = "/home/akhila/fuzzer_packages/fuzzedpackages/MESS/inst/testfiles/hwe_frequencies/libFuzzer_hwe_frequencies/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_min_alleles.qs";
  qs::c_qsave(min_alleles,min_alleles_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "min_alleles values: "<< min_alleles << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    hwe_frequencies(allele1,allele2,min_alleles[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
