// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// networkflow_DeepState_TestHarness_generation.cpp and networkflow_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List networkflow(NumericMatrix a, NumericMatrix b, NumericMatrix C, int threads);

TEST(transport_deepstate_test,networkflow_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix a  = RcppDeepState_NumericMatrix();
  std::string a_t = "/home/akhila/fuzzer_packages/fuzzedpackages/transport/inst/testfiles/networkflow/libFuzzer_networkflow/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_a.qs";
  qs::c_qsave(a,a_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "a values: "<< a << std::endl;
  NumericMatrix b  = RcppDeepState_NumericMatrix();
  std::string b_t = "/home/akhila/fuzzer_packages/fuzzedpackages/transport/inst/testfiles/networkflow/libFuzzer_networkflow/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_b.qs";
  qs::c_qsave(b,b_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "b values: "<< b << std::endl;
  NumericMatrix C  = RcppDeepState_NumericMatrix();
  std::string C_t = "/home/akhila/fuzzer_packages/fuzzedpackages/transport/inst/testfiles/networkflow/libFuzzer_networkflow/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_C.qs";
  qs::c_qsave(C,C_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "C values: "<< C << std::endl;
  IntegerVector threads(1);
  threads[0]  = RcppDeepState_int();
  std::string threads_t = "/home/akhila/fuzzer_packages/fuzzedpackages/transport/inst/testfiles/networkflow/libFuzzer_networkflow/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_threads.qs";
  qs::c_qsave(threads,threads_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "threads values: "<< threads << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    networkflow(a,b,C,threads[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
