// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// marginCombo_DeepState_TestHarness_generation.cpp and marginCombo_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix marginCombo(NumericVector alphavec, NumericMatrix mc);

TEST(lcopula_deepstate_test,marginCombo_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector alphavec  = RcppDeepState_NumericVector();
  std::string alphavec_t = "/home/akhila/fuzzer_packages/fuzzedpackages/lcopula/inst/testfiles/marginCombo/libFuzzer_marginCombo/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_alphavec.qs";
  qs::c_qsave(alphavec,alphavec_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "alphavec values: "<< alphavec << std::endl;
  NumericMatrix mc  = RcppDeepState_NumericMatrix();
  std::string mc_t = "/home/akhila/fuzzer_packages/fuzzedpackages/lcopula/inst/testfiles/marginCombo/libFuzzer_marginCombo/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_mc.qs";
  qs::c_qsave(mc,mc_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "mc values: "<< mc << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    marginCombo(alphavec,mc);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
