// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// segregationcalc_DeepState_TestHarness_generation.cpp and segregationcalc_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector segregationcalc(NumericMatrix distmat, NumericVector grouppop, NumericVector fullpop);

TEST(redist_deepstate_test,segregationcalc_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix distmat  = RcppDeepState_NumericMatrix();
  std::string distmat_t = "/home/akhila/fuzzer_packages/fuzzedpackages/redist/inst/testfiles/segregationcalc/AFL_segregationcalc/afl_inputs/" + std::to_string(t) + "_distmat.qs";
  qs::c_qsave(distmat,distmat_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "distmat values: "<< distmat << std::endl;
  NumericVector grouppop  = RcppDeepState_NumericVector();
  std::string grouppop_t = "/home/akhila/fuzzer_packages/fuzzedpackages/redist/inst/testfiles/segregationcalc/AFL_segregationcalc/afl_inputs/" + std::to_string(t) + "_grouppop.qs";
  qs::c_qsave(grouppop,grouppop_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "grouppop values: "<< grouppop << std::endl;
  NumericVector fullpop  = RcppDeepState_NumericVector();
  std::string fullpop_t = "/home/akhila/fuzzer_packages/fuzzedpackages/redist/inst/testfiles/segregationcalc/AFL_segregationcalc/afl_inputs/" + std::to_string(t) + "_fullpop.qs";
  qs::c_qsave(fullpop,fullpop_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "fullpop values: "<< fullpop << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    segregationcalc(distmat,grouppop,fullpop);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
