// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// AllNeighboursTri__DeepState_TestHarness_generation.cpp and AllNeighboursTri__DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix AllNeighboursTri_(NumericMatrix allFaces, NumericVector div);

TEST(icosa_deepstate_test,AllNeighboursTri__test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix allFaces  = RcppDeepState_NumericMatrix();
  std::string allFaces_t = "/home/akhila/fuzzer_packages/fuzzedpackages/icosa/inst/testfiles/AllNeighboursTri_/AFL_AllNeighboursTri_/afl_inputs/" + std::to_string(t) + "_allFaces.qs";
  qs::c_qsave(allFaces,allFaces_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "allFaces values: "<< allFaces << std::endl;
  NumericVector div  = RcppDeepState_NumericVector();
  std::string div_t = "/home/akhila/fuzzer_packages/fuzzedpackages/icosa/inst/testfiles/AllNeighboursTri_/AFL_AllNeighboursTri_/afl_inputs/" + std::to_string(t) + "_div.qs";
  qs::c_qsave(div,div_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "div values: "<< div << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    AllNeighboursTri_(allFaces,div);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
