// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// do_in_int_DeepState_TestHarness_generation.cpp and do_in_int_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

bool do_in_int(int x, IntegerVector table);

TEST(hutilscpp_deepstate_test,do_in_int_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector x(1);
  x[0]  = RcppDeepState_int();
  std::string x_t = "/home/akhila/fuzzer_packages/fuzzedpackages/hutilscpp/inst/testfiles/do_in_int/AFL_do_in_int/afl_inputs/" + std::to_string(t) + "_x.qs";
  qs::c_qsave(x,x_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  IntegerVector table  = RcppDeepState_IntegerVector();
  std::string table_t = "/home/akhila/fuzzer_packages/fuzzedpackages/hutilscpp/inst/testfiles/do_in_int/AFL_do_in_int/afl_inputs/" + std::to_string(t) + "_table.qs";
  qs::c_qsave(table,table_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "table values: "<< table << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    do_in_int(x[0],table);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
