// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// C_GP_cpp_DeepState_TestHarness_generation.cpp and C_GP_cpp_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix C_GP_cpp(NumericMatrix design, NumericVector response, NumericVector theta, NumericMatrix Ki, int ct);

TEST(activegp_deepstate_test,C_GP_cpp_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix design  = RcppDeepState_NumericMatrix();
  std::string design_t = "/home/akhila/fuzzer_packages/fuzzedpackages/activegp/inst/testfiles/C_GP_cpp/libFuzzer_C_GP_cpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_design.qs";
  qs::c_qsave(design,design_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "design values: "<< design << std::endl;
  NumericVector response  = RcppDeepState_NumericVector();
  std::string response_t = "/home/akhila/fuzzer_packages/fuzzedpackages/activegp/inst/testfiles/C_GP_cpp/libFuzzer_C_GP_cpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_response.qs";
  qs::c_qsave(response,response_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "response values: "<< response << std::endl;
  NumericVector theta  = RcppDeepState_NumericVector();
  std::string theta_t = "/home/akhila/fuzzer_packages/fuzzedpackages/activegp/inst/testfiles/C_GP_cpp/libFuzzer_C_GP_cpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_theta.qs";
  qs::c_qsave(theta,theta_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "theta values: "<< theta << std::endl;
  NumericMatrix Ki  = RcppDeepState_NumericMatrix();
  std::string Ki_t = "/home/akhila/fuzzer_packages/fuzzedpackages/activegp/inst/testfiles/C_GP_cpp/libFuzzer_C_GP_cpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_Ki.qs";
  qs::c_qsave(Ki,Ki_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Ki values: "<< Ki << std::endl;
  IntegerVector ct(1);
  ct[0]  = RcppDeepState_int();
  std::string ct_t = "/home/akhila/fuzzer_packages/fuzzedpackages/activegp/inst/testfiles/C_GP_cpp/libFuzzer_C_GP_cpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_ct.qs";
  qs::c_qsave(ct,ct_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ct values: "<< ct << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    C_GP_cpp(design,response,theta,Ki,ct[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
