# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Cexptr <- function(n, lambda, range) {
    .Call('_RGeode_Cexptr', PACKAGE = 'RGeode', n, lambda, range)
}

Cgammatr <- function(n, A, B, range) {
    .Call('_RGeode_Cgammatr', PACKAGE = 'RGeode', n, A, B, range)
}

CgenerateTau_root <- function(U, t, a, d) {
    .Call('_RGeode_CgenerateTau_root', PACKAGE = 'RGeode', U, t, a, d)
}

CgenerateU_root <- function(prodTau, N, SIGMAS, Z) {
    .Call('_RGeode_CgenerateU_root', PACKAGE = 'RGeode', prodTau, N, SIGMAS, Z)
}

