// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// all_quartets_DeepState_TestHarness_generation.cpp and all_quartets_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

IntegerMatrix all_quartets(IntegerVector nTips);

TEST(Quartet_deepstate_test,all_quartets_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector nTips  = RcppDeepState_IntegerVector();
  std::string nTips_t = "/home/akhila/fuzzer_packages/fuzzedpackages/Quartet/inst/testfiles/all_quartets/AFL_all_quartets/afl_inputs/" + std::to_string(t) + "_nTips.qs";
  qs::c_qsave(nTips,nTips_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nTips values: "<< nTips << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    all_quartets(nTips);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
