// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// buildMatrixNumeric_DeepState_TestHarness_generation.cpp and buildMatrixNumeric_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

SEXP buildMatrixNumeric(CharacterVector v, IntegerVector rowInd, IntegerVector colInd, CharacterVector colNames, int nRows, int nCols);

TEST(openxlsx_deepstate_test,buildMatrixNumeric_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  CharacterVector v  = RcppDeepState_CharacterVector();
  std::string v_t = "/home/akhila/fuzzer_packages/fuzzedpackages/openxlsx/inst/testfiles/buildMatrixNumeric/AFL_buildMatrixNumeric/afl_inputs/" + std::to_string(t) + "_v.qs";
  qs::c_qsave(v,v_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "v values: "<< v << std::endl;
  IntegerVector rowInd  = RcppDeepState_IntegerVector();
  std::string rowInd_t = "/home/akhila/fuzzer_packages/fuzzedpackages/openxlsx/inst/testfiles/buildMatrixNumeric/AFL_buildMatrixNumeric/afl_inputs/" + std::to_string(t) + "_rowInd.qs";
  qs::c_qsave(rowInd,rowInd_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rowInd values: "<< rowInd << std::endl;
  IntegerVector colInd  = RcppDeepState_IntegerVector();
  std::string colInd_t = "/home/akhila/fuzzer_packages/fuzzedpackages/openxlsx/inst/testfiles/buildMatrixNumeric/AFL_buildMatrixNumeric/afl_inputs/" + std::to_string(t) + "_colInd.qs";
  qs::c_qsave(colInd,colInd_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "colInd values: "<< colInd << std::endl;
  CharacterVector colNames  = RcppDeepState_CharacterVector();
  std::string colNames_t = "/home/akhila/fuzzer_packages/fuzzedpackages/openxlsx/inst/testfiles/buildMatrixNumeric/AFL_buildMatrixNumeric/afl_inputs/" + std::to_string(t) + "_colNames.qs";
  qs::c_qsave(colNames,colNames_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "colNames values: "<< colNames << std::endl;
  IntegerVector nRows(1);
  nRows[0]  = RcppDeepState_int();
  std::string nRows_t = "/home/akhila/fuzzer_packages/fuzzedpackages/openxlsx/inst/testfiles/buildMatrixNumeric/AFL_buildMatrixNumeric/afl_inputs/" + std::to_string(t) + "_nRows.qs";
  qs::c_qsave(nRows,nRows_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nRows values: "<< nRows << std::endl;
  IntegerVector nCols(1);
  nCols[0]  = RcppDeepState_int();
  std::string nCols_t = "/home/akhila/fuzzer_packages/fuzzedpackages/openxlsx/inst/testfiles/buildMatrixNumeric/AFL_buildMatrixNumeric/afl_inputs/" + std::to_string(t) + "_nCols.qs";
  qs::c_qsave(nCols,nCols_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nCols values: "<< nCols << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    buildMatrixNumeric(v,rowInd,colInd,colNames,nRows[0],nCols[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
