// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// kndksum_DeepState_TestHarness_generation.cpp and kndksum_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix kndksum(NumericVector x, NumericVector y, NumericVector x_eval, double h, NumericVector betas, NumericVector Counts);

TEST(FKSUM_deepstate_test,kndksum_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector x  = RcppDeepState_NumericVector();
  std::string x_t = "/home/akhila/fuzzer_packages/fuzzedpackages/FKSUM/inst/testfiles/kndksum/libFuzzer_kndksum/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_x.qs";
  qs::c_qsave(x,x_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  NumericVector y  = RcppDeepState_NumericVector();
  std::string y_t = "/home/akhila/fuzzer_packages/fuzzedpackages/FKSUM/inst/testfiles/kndksum/libFuzzer_kndksum/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_y.qs";
  qs::c_qsave(y,y_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "y values: "<< y << std::endl;
  NumericVector x_eval  = RcppDeepState_NumericVector();
  std::string x_t = "/home/akhila/fuzzer_packages/fuzzedpackages/FKSUM/inst/testfiles/kndksum/libFuzzer_kndksum/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_x.qs";
  std::string x_eval_t = "/home/akhila/fuzzer_packages/fuzzedpackages/FKSUM/inst/testfiles/kndksum/libFuzzer_kndksum/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_x_eval.qs";
  qs::c_qsave(x_eval,x_eval_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x_eval values: "<< x_eval << std::endl;
  NumericVector h(1);
  h[0]  = RcppDeepState_double();
  std::string h_t = "/home/akhila/fuzzer_packages/fuzzedpackages/FKSUM/inst/testfiles/kndksum/libFuzzer_kndksum/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_h.qs";
  qs::c_qsave(h,h_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "h values: "<< h << std::endl;
  NumericVector betas  = RcppDeepState_NumericVector();
  std::string betas_t = "/home/akhila/fuzzer_packages/fuzzedpackages/FKSUM/inst/testfiles/kndksum/libFuzzer_kndksum/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_betas.qs";
  qs::c_qsave(betas,betas_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "betas values: "<< betas << std::endl;
  NumericVector Counts  = RcppDeepState_NumericVector();
  std::string Counts_t = "/home/akhila/fuzzer_packages/fuzzedpackages/FKSUM/inst/testfiles/kndksum/libFuzzer_kndksum/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_Counts.qs";
  qs::c_qsave(Counts,Counts_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Counts values: "<< Counts << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    kndksum(x,y,x_eval,h[0],betas,Counts);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
