// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// hclustMergeOrder_DeepState_TestHarness_generation.cpp and hclustMergeOrder_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List hclustMergeOrder(NumericMatrix mst, IntegerVector o);

TEST(dbscan_deepstate_test,hclustMergeOrder_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix mst  = RcppDeepState_NumericMatrix();
  std::string mst_t = "/home/akhila/fuzzer_packages/fuzzedpackages/dbscan/inst/testfiles/hclustMergeOrder/AFL_hclustMergeOrder/afl_inputs/" + std::to_string(t) + "_mst.qs";
  qs::c_qsave(mst,mst_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "mst values: "<< mst << std::endl;
  IntegerVector o  = RcppDeepState_IntegerVector();
  std::string o_t = "/home/akhila/fuzzer_packages/fuzzedpackages/dbscan/inst/testfiles/hclustMergeOrder/AFL_hclustMergeOrder/afl_inputs/" + std::to_string(t) + "_o.qs";
  qs::c_qsave(o,o_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "o values: "<< o << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    hclustMergeOrder(mst,o);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
