// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// sb_DeepState_TestHarness_generation.cpp and sb_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector sb(NumericVector m1, NumericVector bg, IntegerVector d, IntegerVector e);

TEST(trackdem_deepstate_test,sb_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector m1  = RcppDeepState_NumericVector();
  std::string m1_t = "/home/akhila/fuzzer_packages/fuzzedpackages/trackdem/inst/testfiles/sb/libFuzzer_sb/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_m1.qs";
  qs::c_qsave(m1,m1_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "m1 values: "<< m1 << std::endl;
  NumericVector bg  = RcppDeepState_NumericVector();
  std::string bg_t = "/home/akhila/fuzzer_packages/fuzzedpackages/trackdem/inst/testfiles/sb/libFuzzer_sb/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_bg.qs";
  qs::c_qsave(bg,bg_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "bg values: "<< bg << std::endl;
  IntegerVector d  = RcppDeepState_IntegerVector();
  std::string d_t = "/home/akhila/fuzzer_packages/fuzzedpackages/trackdem/inst/testfiles/sb/libFuzzer_sb/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_d.qs";
  qs::c_qsave(d,d_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "d values: "<< d << std::endl;
  IntegerVector e  = RcppDeepState_IntegerVector();
  std::string e_t = "/home/akhila/fuzzer_packages/fuzzedpackages/trackdem/inst/testfiles/sb/libFuzzer_sb/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_e.qs";
  qs::c_qsave(e,e_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "e values: "<< e << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    sb(m1,bg,d,e);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
