// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// coreFromDist_DeepState_TestHarness_generation.cpp and coreFromDist_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector coreFromDist(const NumericVector dist, const int n, const int minPts);

TEST(dbscan_deepstate_test,coreFromDist_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector dist  = RcppDeepState_NumericVector();
  std::string dist_t = "/home/akhila/fuzzer_packages/fuzzedpackages/dbscan/inst/testfiles/coreFromDist/AFL_coreFromDist/afl_inputs/" + std::to_string(t) + "_dist.qs";
  qs::c_qsave(dist,dist_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "dist values: "<< dist << std::endl;
  IntegerVector n(1);
  n[0]  = RcppDeepState_int();
  std::string n_t = "/home/akhila/fuzzer_packages/fuzzedpackages/dbscan/inst/testfiles/coreFromDist/AFL_coreFromDist/afl_inputs/" + std::to_string(t) + "_n.qs";
  qs::c_qsave(n,n_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "n values: "<< n << std::endl;
  IntegerVector minPts(1);
  minPts[0]  = RcppDeepState_int();
  std::string minPts_t = "/home/akhila/fuzzer_packages/fuzzedpackages/dbscan/inst/testfiles/coreFromDist/AFL_coreFromDist/afl_inputs/" + std::to_string(t) + "_minPts.qs";
  qs::c_qsave(minPts,minPts_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "minPts values: "<< minPts << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    coreFromDist(dist,n[0],minPts[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
