// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// constant_at_interpolator_DeepState_TestHarness_generation.cpp and constant_at_interpolator_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

CharacterVector constant_at_interpolator(CharacterVector from, CharacterVector to, NumericVector at, CharacterVector ease);

TEST(tweenr_deepstate_test,constant_at_interpolator_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  CharacterVector from  = RcppDeepState_CharacterVector();
  std::string from_t = "/home/akhila/fuzzer_packages/fuzzedpackages/tweenr/inst/testfiles/constant_at_interpolator/AFL_constant_at_interpolator/afl_inputs/" + std::to_string(t) + "_from.qs";
  qs::c_qsave(from,from_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "from values: "<< from << std::endl;
  CharacterVector to  = RcppDeepState_CharacterVector();
  std::string to_t = "/home/akhila/fuzzer_packages/fuzzedpackages/tweenr/inst/testfiles/constant_at_interpolator/AFL_constant_at_interpolator/afl_inputs/" + std::to_string(t) + "_to.qs";
  qs::c_qsave(to,to_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "to values: "<< to << std::endl;
  NumericVector at  = RcppDeepState_NumericVector();
  std::string at_t = "/home/akhila/fuzzer_packages/fuzzedpackages/tweenr/inst/testfiles/constant_at_interpolator/AFL_constant_at_interpolator/afl_inputs/" + std::to_string(t) + "_at.qs";
  qs::c_qsave(at,at_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "at values: "<< at << std::endl;
  CharacterVector ease  = RcppDeepState_CharacterVector();
  std::string ease_t = "/home/akhila/fuzzer_packages/fuzzedpackages/tweenr/inst/testfiles/constant_at_interpolator/AFL_constant_at_interpolator/afl_inputs/" + std::to_string(t) + "_ease.qs";
  qs::c_qsave(ease,ease_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ease values: "<< ease << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    constant_at_interpolator(from,to,at,ease);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
